"""gaps — aggregate per-use-case gap sections into the live MASTER_GAPS.md.

Integrate agents write pipeline-state/gaps/<slug>.md using exact tag markers;
this counts + concatenates them. Same contract as scripts/build-master-gaps.sh,
ported to Python so the whole pipeline is one language.
"""
from __future__ import annotations
import os, re
from datetime import datetime
from pathlib import Path

MARKERS = {
    "docs-mcp": ["coverageGap:", "staleness:", "docsEscape:"],
    "skills": ["missedTrigger:", "falseTrigger:", "variant:", "hallucination:"],
}


def _count(gaps_dir: Path, marker: str) -> int:
    n = 0
    for f in gaps_dir.glob("*.md"):
        n += len(re.findall(re.escape(marker), f.read_text()))
    return n


def rebuild(settings: dict) -> dict:
    gaps_dir = Path(os.path.expanduser(settings["gaps_dir"]))
    gaps_dir.mkdir(parents=True, exist_ok=True)
    out = Path(os.path.expanduser(settings["master_gaps"]))
    counts = {m: _count(gaps_dir, m) for grp in MARKERS.values() for m in grp}
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# MASTER_GAPS.md — live gaps ledger (MCP + skills)", "",
        f"> Auto-generated by `pipeline/lib/gaps.py`. Regenerated: **{ts}**.",
        "> Source: `pipeline-state/gaps/<slug>.md` (written by integrate/verify stages).", "",
        "| Bucket | Markers | Count |", "|---|---|--:|",
        f"| docs-mcp | coverageGap / staleness / docsEscape | {counts['coverageGap:']} / {counts['staleness:']} / {counts['docsEscape:']} |",
        f"| skills | missedTrigger / falseTrigger / variant / hallucination | "
        f"{counts['missedTrigger:']} / {counts['falseTrigger:']} / {counts['variant:']} / {counts['hallucination:']} |",
        "", "## Known / expected gaps (pre-seeded)",
        "- **missedTrigger: Vue has no `cometchat-vue` skill** → UC5 (Fintech) & UC10 (Event). "
        "Expect no skill to fire on the Vue web slice — record it, don't treat as agent failure.",
        "", "---", "", "## Per-use-case findings",
    ]
    sections = sorted(gaps_dir.glob("*.md"))
    if sections:
        for f in sections:
            lines += ["", f.read_text().rstrip(), ""]
    else:
        lines += ["", "_No section files yet — populated once integrate stages run._"]
    lines += ["", "---", "_Rollup feeds aggregate.py → rankedFixBacklog._"]
    out.write_text("\n".join(lines))
    return {"masterGaps": str(out), "counts": counts}
