#!/usr/bin/env python3
"""run_usecase.py — deterministic stage worker for the STEP4 hybrid pipeline.

One stage per invocation; exits after each. Holds NO state between calls — all
state is on disk (git repo in work_root/<slug>/, JSON in _reports/ + pipeline-state/).
The ONLY LLM calls are the per-component `claude -p` codegen + one judge; every
gate is deterministic Python. Never blocks on input() — the conductor (session or
batch_runner.py) sequences stages and holds the human checkpoints.

Stages:  build → boot → push-main → integrate → verify → push-branch
Exit:    0 ok+gate-pass · 2 gate-fail (conductor halts) · 3 stage error

Usage:   python3 run_usecase.py --use-case mkt --stage build
"""
from __future__ import annotations
import argparse, json, os, subprocess, sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
import time  # noqa: E402
from lib import claude_runner, gates, prompts, state, verify, gaps, readiness, mobile, cometchat, shotreview, selfheal, providers, secrets, obs  # noqa: E402

HERE = Path(__file__).resolve().parent
AUTOMATE_ROOT = HERE.parent
ENV_FILE = AUTOMATE_ROOT / ".env.pipeline"


def uc_env_file(S, uc) -> Path:
    """This use case's OWN CometChat app creds (runs/<slug>/.env.cometchat). Each use case is provisioned
    a SEPARATE CometChat app — account-level keys (automation/APNs/FCM/webhook) stay in the global
    .env.pipeline, but the app-specific APP_ID/REGION/AUTH_KEY/REST_API_KEY come from here so no two use
    cases ever share an app's users/conversations/data."""
    return state.repo_dir(S, uc["slug"]) / ".env.cometchat"


def _load_kv_into_os(path: Path):
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                if v.strip():
                    os.environ[k.strip()] = v.strip()


def load_envfile_into_os(S=None, uc=None):
    """Load the global sweep creds, then OVERLAY this use case's OWN provisioned-app creds (per-UC wins),
    so codegen/verify/demo bind to the use case's own CometChat app — not a shared one. COMETCHAT_ENV_FILE
    points at the per-UC file when it exists (so `_cfg` reads + the secret scan use the right app)."""
    _load_kv_into_os(ENV_FILE)
    active = ENV_FILE
    if S is not None and uc is not None:
        ue = uc_env_file(S, uc)
        if ue.exists():
            _load_kv_into_os(ue); active = ue
    os.environ["COMETCHAT_ENV_FILE"] = str(active)


def load(name):
    return json.loads((HERE / "config" / name).read_text())


def e2e_password(uc):
    """The shared seed password for a use case. Default is SLUG-DERIVED (mkt→Mkt@seed2026!,
    com→Com@seed2026!) matching the requirements-pinned format — NOT the mkt-hardcoded literal, which
    401s on every other use case's seeded accounts (confirmed: com uses Com@seed2026!)."""
    return uc.get("e2ePassword") or f"{uc['slug'].capitalize()}@seed2026!"


def git(repo: Path, *args) -> tuple[int, str]:
    cmd = ["git", "-c", "user.email=pipeline@step4.local", "-c", "user.name=step4-pipeline", *args]
    p = subprocess.run(cmd, cwd=str(repo), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return p.returncode, p.stdout


# Written at repo init so `git add -A` NEVER tracks deps/build junk/secrets. Without this the baseline
# codegen commits node_modules + .venv + build outputs (UC1 hit 83k tracked files / 337M, ~95% junk)
# and every rebuild churns thousands of artifacts. Keep .example templates; real .env is build-time only.
GITIGNORE = """\
# Dependencies
node_modules/

# Python virtualenv
.venv/
venv/

# Native build outputs (regenerated by expo prebuild + gradle/xcode)
**/build/
.gradle/
android/.gradle/
android/app/build/
ios/build/
ios/Pods/
**/DerivedData/
**/.cxx/
.expo/
.kotlin/

# Web build output
.next/
out/

# Secrets — build-time creds are injected by the pipeline (mobile.write_cometchat_env). Commit only .example.
.env
!.env.example
# Generated cred files (self-heal writes the REAL provisioned creds here) — must never be pushed.
.dart_define.json
local.properties
**/local.properties
# Per-use-case CometChat app creds (this repo's OWN provisioned app) — live authKey/restApiKey.
.env.cometchat
cometchat-app-config.json

# Pipeline / demo artifacts (not app source)
_demo/
_logs/
_reports/
pipeline-state/
test-results/

# Ad-hoc e2e scripts copied into web/ at runtime
web/_*.mjs

# Python bytecode / OS cruft
__pycache__/
*.pyc
.DS_Store
*.log
"""


def ensure_repo(repo: Path) -> None:
    """Init the repo on `main` AND write .gitignore before any `git add -A` runs, so no use case
    ever commits node_modules/.venv/build artifacts/secrets. Idempotent — safe to call repeatedly.
    For a pre-existing repo that already tracked junk (e.g. re-run), untrack whatever the fresh
    .gitignore now excludes (files stay on disk; only the index is cleaned)."""
    fresh = not (repo / ".git").exists()
    if fresh:
        git(repo, "init", "-q"); git(repo, "checkout", "-q", "-b", "main")
    gi = repo / ".gitignore"
    cur = gi.read_text() if gi.exists() else ""
    # refresh a STALE ignore too (an existing repo created before .dart_define.json/local.properties
    # were added) so newly-ignored cred files are untracked below — not just fresh-repo creation.
    if not gi.exists() or "node_modules/" not in cur or ".dart_define.json" not in cur:
        gi.write_text(GITIGNORE)
    if not fresh:  # existing repo — drop any tracked files the .gitignore now ignores
        code, tracked = git(repo, "ls-files", "-ci", "--exclude-standard")
        if code == 0 and tracked.strip():
            sh_shell(f"cd {repo!s} && git ls-files -ci --exclude-standard -z | "
                     f"xargs -0 git rm -r --cached --quiet 2>/dev/null || true")


def sh(*args, cwd=None, timeout=600) -> tuple[int, str]:
    p = subprocess.run(list(args), cwd=cwd, text=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return p.returncode, p.stdout


def sh_shell(cmd, timeout=1200) -> tuple[int, str]:
    p = subprocess.run(cmd, shell=True, text=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return p.returncode, p.stdout


def augment_path(S):
    """Make self-installed tools (maestro, android) findable by later stages."""
    import shutil as _sh
    for p in S.get("bootstrap", {}).get("extra_path", []):
        pe = os.path.expanduser(p)
        if pe not in os.environ.get("PATH", ""):
            os.environ["PATH"] = pe + os.pathsep + os.environ.get("PATH", "")
    return _sh


def bootstrap_tools(S) -> dict:
    """Idempotent Phase-0 installs — only run when a tool is actually missing."""
    import shutil
    b = S.get("bootstrap", {}); res = {}
    have_maestro = shutil.which("maestro") or Path(os.path.expanduser("~/.maestro/bin/maestro")).exists()
    if not have_maestro and b.get("maestro_install"):
        code, _ = sh_shell(b["maestro_install"]); res["maestro"] = (code == 0)
    else:
        res["maestro"] = bool(have_maestro)
    # playwright browsers (global cache); the @playwright/test pkg is added per-web-project by the coder
    if b.get("playwright_install"):
        code, _ = sh_shell(b["playwright_install"]); res["playwright"] = (code == 0)
    return res


def die_gate(msg):
    print(f"GATE-FAIL: {msg}", file=sys.stderr); sys.exit(2)


def fail_gate(S, uc, stage, summary, signals, *, gate=None, err="", evidence=None):
    """Record a failure with a DETERMINISTICALLY-CLASSIFIED cause (infra/agent/harness/skills/setup)
    before halting, so a boot/harness failure is never mislabelled 'skills' and poisons the gaps
    ledger. Use in the stages where the cause actually matters (verify/integrate/boot/demo)."""
    cause = obs.record_failure(S, uc["slug"], stage, gate=gate or stage, summary=summary,
                               signals=signals, err=err, evidence=evidence)
    print(f"GATE-FAIL[{cause}]: {summary} tag={cause}", file=sys.stderr)
    sys.exit(2)


def secret_scan_or_die(S, uc, repo, stage):
    """The STEP4 §4.6 pre-push gate that was promised but never implemented: block the push if any
    real secret VALUE (from .env.pipeline) appears in a TRACKED file. Runs before every git push."""
    load_envfile_into_os(S, uc)
    scan = secrets.scan_repo(repo, str(uc_env_file(S, uc)))
    if not scan.get("clean"):
        fail_gate(S, uc, stage,
                  f"{stage}:{uc['slug']} SECRET-SCAN BLOCKED push — {scan.get('hits') or scan.get('error')}",
                  {"exit": 2}, gate="secret-scan", evidence=[str(h) for h in scan.get("hits", [])])


# ===================== STAGES =====================
def _only_filter(comps):
    """Scope a stage's component list to STEP4_ONLY (comma-separated kinds or names),
    e.g. STEP4_ONLY=web builds/integrates ONLY the web slice and leaves every other
    component (and its committed integration) untouched. Empty env -> no filtering."""
    only = {x.strip() for x in os.environ.get("STEP4_ONLY", "").split(",") if x.strip()}
    if not only:
        return comps
    kept = [c for c in comps if c["kind"] in only or c["name"] in only]
    if kept:
        print(f"  [scoped] STEP4_ONLY={sorted(only)} -> {[c['name'] for c in kept]}")
    return kept


def _spec_depth_check(text: str) -> tuple[bool, list[str]]:
    """Gate the generated spec against the DEPTH STANDARD (requirements.md.tmpl §A-E). A spec that only
    pins the fixed login→chat→call flow with a thin seed silently produces a SHALLOW app (the pipeline
    gates on compiles+boots, not depth). Lenient, synonym-tolerant markers — a spec that actually follows
    the template passes; a genuinely shallow one (no CRUD, no states, no images, no UI states) fails.
    Returns (ok, missing-markers)."""
    t = text.lower()
    checks = {
        "full CRUD (create/edit/delete in-app)": "crud" in t or all(w in t for w in ("create", "edit", "delete")),
        "entity state machine (status + transitions)":
            any(w in t for w in ("status", "state machine")) and ("→" in text or "->" in t or "transition" in t),
        "user avatars (avatar_url)": "avatar" in t,
        "entity images (image_url)": "image_url" in t or ("image" in t and "url" in t),
        "image/media chat message": any(w in t for w in ("image message", "media message", "image/media")),
        "empty/loading/error UI states": "empty" in t and "loading" in t and ("retry" in t or "error state" in t),
    }
    missing = [k for k, ok in checks.items() if not ok]
    return (not missing, missing)


def _generate_spec_with_depth(S, uc, req_file, repo, max_tries: int = 2) -> bool:
    """Generate the spec-pin and ENFORCE the DEPTH STANDARD. If the first draft is shallow, regenerate
    ONCE with the missing markers called out (self-heal), then gate. A spec that stays shallow after the
    retry halts preflight (tag=agent → codegen note, not a skills gap) so no shallow app is ever built."""
    base_prompt = prompts.render_requirements(S, uc)
    missing: list[str] = []
    for attempt in range(max_tries):
        prompt = base_prompt if attempt == 0 else (
            base_prompt + f"\n\n⚠ YOUR PREVIOUS DRAFT WAS REJECTED AS SHALLOW — it did not satisfy the DEPTH "
            f"STANDARD. It was MISSING: {', '.join(missing)}. Rewrite requirements/{uc['slug']}.md so EVERY "
            f"one of those is explicitly present (see DEPTH STANDARD A-E). Overwrite the existing file.")
        claude_runner.run_headless(prompt, settings=S, phase="A", cwd=HERE, model_key="spec",
                                   label=f"spec-{uc['slug']}" + ("" if attempt == 0 else f"-retry{attempt}"),
                                   log_dir=repo / "_logs")
        if not (req_file.exists() and req_file.stat().st_size > 200):
            continue
        ok, missing = _spec_depth_check(req_file.read_text())
        obs.event(S, uc["slug"], "preflight", "spec_depth", attempt=attempt, ok=ok, missing=missing)
        if ok:
            if attempt:
                print(f"  ✔ spec-depth: {uc['slug']} passed on retry {attempt}")
            return True
        print(f"  ⚠ spec-depth: {uc['slug']} draft {attempt + 1} SHALLOW — missing {missing}; "
              f"{'regenerating' if attempt + 1 < max_tries else 'out of retries'}")
    if req_file.exists() and req_file.stat().st_size > 200:
        die_gate(f"preflight:{uc['slug']} spec still SHALLOW after {max_tries} tries — missing {missing}; "
                 f"DEPTH STANDARD (requirements.md.tmpl §A-E) not met tag=agent")
    return False


def stage_preflight(S, uc):
    """Phase 0 — initialise + stack-readiness gate + generate the spec-pin (req:baseline).
    No codegen tokens are spent past here unless this use case's stacks are actually buildable."""
    comps = prompts.expand_components(uc)
    rd = readiness.check(uc, comps, need_docker=True)
    # self-provision the e2e toolchain (installs only what's missing) so verify isn't blocked later
    boot_tools = bootstrap_tools(S)
    # initialise workspace + git
    repo = state.repo_dir(S, uc["slug"]); repo.mkdir(parents=True, exist_ok=True)
    ensure_repo(repo)  # init on main + write .gitignore BEFORE any codegen/add can track junk
    # generate the spec-pin if missing (this is "requirements build once implementation starts")
    req_file = HERE / "requirements" / f"{uc['slug']}.md"
    spec_generated = req_file.exists()
    if rd["ready"] and not spec_generated:
        req_file.parent.mkdir(parents=True, exist_ok=True)
        # Generate + ENFORCE the DEPTH STANDARD (regenerate-once self-heal, then gate). Existing specs
        # (del/com/mkt) already exist → skipped here, so this only deepens dat forward.
        spec_generated = _generate_spec_with_depth(S, uc, req_file, repo)
    res = {"useCase": uc["name"], "slug": uc["slug"], "ready": rd["ready"], "missing": rd["missing"],
           "byComponent": rd["byComponent"], "workspaceInit": (repo / ".git").exists(),
           "e2eTools": boot_tools, "specGenerated": spec_generated, "specFile": str(req_file)}
    state.write(S, uc["slug"], "preflight", res)
    if not rd["ready"]:
        die_gate(f"preflight:{uc['slug']} not build-ready — missing {rd['missing']} tag=agent")
    print(f"OK preflight:{uc['slug']} ready; spec={'yes' if spec_generated else 'PENDING'}"); return res


def stage_provision(S, uc):
    """Provision a SEPARATE CometChat app for THIS use case (not a shared one): use the account-level
    automation/management keys to create app `step4-<slug>`, capture its APP_ID/REGION/AUTH_KEY/
    REST_API_KEY, and write them to the per-UC file runs/<slug>/.env.cometchat (+ cometchat-app-config.json).
    Idempotent per use case: if the per-UC file already names a valid app, no-op."""
    repo = state.repo_dir(S, uc["slug"]); repo.mkdir(parents=True, exist_ok=True)
    ue = uc_env_file(S, uc)
    load_envfile_into_os(S, uc)                         # global account keys (automation/APNs/FCM/webhook)
    if ue.exists() and cometchat._cfg(str(ue)).get("COMETCHAT_APP_ID"):
        res = {"appIdSet": True, "skipped": "already provisioned (per-UC app)", "appIdFile": str(ue)}
        state.write(S, uc["slug"], "provision-app", res)
        print(f"OK provision-app: {uc['slug']} already has its own app ({ue.name}) — no-op"); return res
    # Do NOT let the agent reuse a shared app: hide any shared app-specific keys — only the ACCOUNT
    # automation keys should be visible, forcing a fresh per-UC app.
    for k in ("COMETCHAT_APP_ID", "COMETCHAT_AUTH_KEY", "COMETCHAT_REST_API_KEY", "COMETCHAT_REGION"):
        os.environ.pop(k, None)
    r = claude_runner.run_headless(prompts.render_provision(S, uc), settings=S, phase="B",
                                   cwd=repo, model_key="provision", label=f"provision-{uc['slug']}",
                                   log_dir=repo / "_logs")
    app_set = ue.exists() and bool(cometchat._cfg(str(ue)).get("COMETCHAT_APP_ID"))
    res = {"appIdSet": app_set, "exitCode": r["exitCode"], "appIdFile": str(ue), "tail": r["tail"]}
    state.write(S, uc["slug"], "provision-app", res)
    if not app_set:
        die_gate(f"provision-app:{uc['slug']} — no per-UC app created at {ue.name}; check "
                 f"COMETCHAT_DASHBOARD_CHECKLIST.md; provisioning residue is a finding tag=docs-mcp")
    load_envfile_into_os(S, uc)                    # now overlay the freshly-provisioned per-UC creds
    print(f"OK provision-app: {uc['slug']} — dedicated app created + creds written to {ue.name}"); return res


def stage_build(S, uc):
    repo = state.repo_dir(S, uc["slug"]); repo.mkdir(parents=True, exist_ok=True)
    logs = repo / "_logs"
    ensure_repo(repo)  # init on main + write .gitignore BEFORE any codegen/add can track junk
    comps, worst, runs = _only_filter(prompts.expand_components(uc)), 0, []
    for c in comps:
        cdir = repo / c["dir"]
        r = claude_runner.run_headless(prompts.render_build(S, uc, c), settings=S, phase="A",
                                       cwd=cdir, model_key="build", label=f"build-{c['name']}", log_dir=logs)
        g = verify.build_gate(c["kind"], cdir)
        # SELF-HEAL: if the gate failed with a known UC1 signature, auto-repair + retry once — no human.
        if g["buildExitCode"] != 0:
            ctx = {"stage": "build", "kind": c["kind"], "stack": c["stack"],
                   "repo_dir": repo, "comp_dir": cdir, "mobile_dir": cdir,
                   "env_file": str(uc_env_file(S, uc)), "integrated": False}
            healed = selfheal.heal(ctx, g["outputTail"])
            if healed:
                print(f"  self-heal build:{c['name']} → {[h['rule'] for h in healed]}; retrying")
                # thread the heal env (e.g. JAVA_HOME=JDK17) into the re-gate — else the fix no-ops
                g = verify.build_gate(c["kind"], cdir, env=ctx.get("env")); g["selfHealed"] = [h["rule"] for h in healed]
        runs.append({**c, **r, **g}); worst = max(worst, g["buildExitCode"])  # compile authoritative; agentOk gates truncation
    sha = ""
    if worst == 0:
        git(repo, "add", "-A"); git(repo, "commit", "-q", "-m", f"baseline {uc['name']} (no CometChat)")
        _, sha = git(repo, "rev-parse", "HEAD"); sha = sha.strip()
    res = {"useCase": uc["name"], "slug": uc["slug"], "stack": uc["archetype"],
           "buildExitCode": worst, "committedSha": sha,
           "components": runs, "outputTail": (runs[-1]["outputTail"] if runs else "")}
    state.write(S, uc["slug"], "build", res)
    if not gates.baseline(res):
        die_gate(f"baseline:{uc['slug']} (buildExit={worst}, sha={'yes' if sha else 'no'}) tag=agent")
    print(f"OK build:{uc['slug']} sha={sha[:9]}"); return res


WEBDRIVER = HERE / "e2e" / "webdriver"           # standalone Playwright (Flutter web has no @playwright/test)
PW_BROWSERS = os.path.expanduser("~/Library/Caches/ms-playwright")


def _web_login_shot_flutter(out_png, role="Member", submit="Sign In") -> bool:
    """LOGGED-IN web shot for a Flutter (CanvasKit) app. Flutter web has no real DOM (the --web-renderer
    html flag was removed in 3.44), so we drive login through the accessibility (flt-semantics) tree the
    app emits via SemanticsBinding.ensureSemantics(): tap the demo-role button, submit, wait for the login
    copy to disappear, screenshot the home. Proves web→backend connectivity (the root shot only proves it
    serves the login screen). Uses the shared pipeline Playwright in e2e/webdriver."""
    driver = WEBDRIVER / "flutter_login_shot.mjs"
    if not driver.exists():
        return False
    if not (WEBDRIVER / "node_modules").exists():   # self-bootstrap the shared Playwright (once)
        print("  installing shared Playwright for web-login driver…")
        subprocess.run(["npm", "install", "--no-audit", "--no-fund"], cwd=str(WEBDRIVER),
                       env={**os.environ, "PLAYWRIGHT_BROWSERS_PATH": PW_BROWSERS},
                       capture_output=True, timeout=300)
        subprocess.run(["npx", "--yes", "playwright", "install", "chromium"], cwd=str(WEBDRIVER),
                       env={**os.environ, "PLAYWRIGHT_BROWSERS_PATH": PW_BROWSERS},
                       capture_output=True, timeout=600)
        if not (WEBDRIVER / "node_modules").exists():
            return False
    env = {**os.environ, "PLAYWRIGHT_BROWSERS_PATH": PW_BROWSERS,
           "URL": "http://localhost:3000/", "ROLE": role, "SUBMIT": submit, "OUT": str(out_png)}
    p = subprocess.run(["node", str(driver)], cwd=str(WEBDRIVER), text=True,
                       capture_output=True, timeout=120, env=env)
    print(f"  web login→home (semantics): {p.stdout.strip()[-160:] or p.stderr.strip()[-160:]}")
    return p.returncode == 0 and Path(out_png).exists()


def _web_shot(repo, out_png) -> bool:
    """Screenshot the served web app ROOT (login screen for auth-gated apps). The LOGGED-IN home is a
    separate shot (_web_login_shot_flutter). Node web (repo/web) uses its own @playwright/test; a Flutter
    (or any repo/web-less) app uses the shared pipeline Playwright in e2e/webdriver."""
    web = repo / "web"
    if not web.exists():
        # Flutter / repo/web-less: plain root shot via the shared driver
        if (WEBDRIVER / "node_modules").exists():
            driver = WEBDRIVER / "root_shot.mjs"
            driver.write_text(
                "import { chromium } from 'playwright'\n"
                "const b = await chromium.launch()\n"
                "const p = await b.newPage({ viewport:{width:1280,height:900} })\n"
                "await p.goto('http://localhost:3000/', { waitUntil:'load' }).catch(()=>{})\n"
                "await p.waitForTimeout(4000)\n"
                f"await p.screenshot({{ path:'{out_png}' }})\n"
                "await b.close()\n")
            env = {**os.environ, "PLAYWRIGHT_BROWSERS_PATH": PW_BROWSERS}
            code = subprocess.run(["node", str(driver)], cwd=str(WEBDRIVER), env=env,
                                  capture_output=True, timeout=120).returncode
            return code == 0 and Path(out_png).exists()
        return False
    script = web / "_shot.mjs"
    script.write_text(
        "import { chromium } from '@playwright/test'\n"
        "const b = await chromium.launch()\n"
        "const p = await b.newPage({ viewport: { width: 1280, height: 900 } })\n"
        "await p.goto('http://localhost:3000/', { waitUntil: 'networkidle' }).catch(()=>{})\n"
        "await p.waitForTimeout(2000)\n"
        f"await p.screenshot({{ path: '{out_png}', fullPage: false }})\n"
        "await b.close()\n")
    code, _ = sh("node", str(script), cwd=str(web), timeout=120)
    script.unlink(missing_ok=True)
    return code == 0 and Path(out_png).exists()


def stage_demo(S, uc):
    """MANUAL-VERIFY: boot web + Android + iOS, screenshot each, and LEAVE EVERYTHING UP
    for hands-on testing. Cleanly torn down by stage_teardown after the human approves.

    Boot-2 (post-integrate) MANDATORY rebuild: stage_demo always does a fresh
    prebuild_clean → gradle/xcode release build, so the apps under manual test are built
    from the CURRENT working tree. When integration has run, we additionally (a) assert the
    tree is on feature/cometchat-integration and (b) GATE on the mobile build compiling — a
    broken integrated build must not silently present stale baseline apps at CP2."""
    repo = state.repo_dir(S, uc["slug"]); V = S["verify"]
    demo = repo / "_demo"; demo.mkdir(exist_ok=True)
    kinds = {c["kind"] for c in prompts.expand_components(uc)}
    integrated = bool(state.read(S, uc["slug"], "integrate"))  # boot-2 iff integrate has run
    if integrated:
        _, branch = git(repo, "rev-parse", "--abbrev-ref", "HEAD")
        branch = branch.strip()
        print(f"boot-2 (integrated): rebuilding apps from branch '{branch}'")
        if branch != "feature/cometchat-integration":
            die_gate(f"demo:{uc['slug']} boot-2 must be on feature/cometchat-integration, on '{branch}' tag=agent")
    shots = {}
    # 1. web + backend via docker — leave up
    is_flutter_web = (repo / "app" / "pubspec.yaml").exists() and not (repo / "web").exists()
    if (repo / "docker-compose.yml").exists():
        if is_flutter_web:   # Flutter web served static — host-build first (empty API_URL → nginx /api proxy)
            providers.host_build_flutter_web(repo / "app", env_file=str(uc_env_file(S, uc)))
        up, _ = verify.compose_up(repo)
        hpaths = V.get("backend_health_paths") or ["/health"]
        verify.health_check(V.get("backend_url", "http://localhost:8080"), hpaths, V["backend_health_timeout_s"])
        if "web" in kinds or is_flutter_web:   # Node web OR Flutter web
            p = str(demo / "web.png")
            shots["web"] = {"ok": _web_shot(repo, p), "path": p}
            if is_flutter_web:   # ALSO drive login via the semantics tree → logged-in home (connectivity proof)
                lp = str(demo / "web-loggedin.png")
                shots["web-loggedin"] = {"ok": _web_login_shot_flutter(lp), "path": lp}
    # 2. mobile / native clients — dispatch to the STACK PROVIDER per component (RN / Flutter /
    #    native Android / native iOS). Each provider self-heals (cleartext + creds), builds, installs,
    #    launches and screenshots — the demo stage is no longer RN-only.
    mobile_calls = {}; plat_app_id = {}
    # API_URL is the scheme://host:port BASE with NO path — the app appends the full route (…/api/…).
    # A base ending in /api double-prefixes → fatal /api/api/... 404. RN inlines its own EXPO_PUBLIC_API_URL.
    api_a = V.get("api_android", "http://10.0.2.2:8080")   # android emulator → host
    api_i = V.get("api_ios", "http://localhost:8080")      # ios simulator → localhost
    for c in prompts.expand_components(uc):
        if c["kind"] not in ("mobile", "app", "android", "ios"):
            continue
        prov = providers.mobile_provider(c["kind"], c["stack"])
        if not prov:
            shots[c["name"]] = {"ok": False, "note": f"no demo provider for {c['kind']}/{c['stack']}"}
            continue
        print(f"demo provider [{prov.family}] for {c['name']} ({c['stack']})…")
        ctx = {"app_dir": repo / c["dir"], "repo_dir": repo, "demo_dir": demo,
               "kind": c["kind"], "stack": c["stack"], "api_android": api_a, "api_ios": api_i,
               "api_web": "", "integrated": integrated, "env_file": str(uc_env_file(S, uc)), "settings": S}
        aid = providers.resolve_app_id(c["kind"], repo / c["dir"])
        for plat, shot in prov.demo(ctx).items():   # android / ios / web
            shots[plat] = shot
            if plat in ("android", "ios"):           # per-platform id (android != ios bundle for Flutter)
                plat_app_id[plat] = shot.get("appId") or aid
    # LOGIN + screenshot the logged-in home for each mobile client that launched OK — proves the app
    # reaches the backend (connectivity), which the launch screen alone doesn't. Uses a seeded account.
    # resolve the chat-test pair from the app's OWN demo accounts (chatPair) when configured — same
    # source of truth as verify, so mobile login/call use accounts the app actually seeded.
    if uc.get("chatPair"):
        _rp = cometchat.seed_and_resolve_pair(str(uc_env_file(S, uc)), uc, V.get("backend_url", "http://localhost:8080"), e2e_password(uc))
        acc_pair = _rp if (_rp.get("web") and _rp["web"][1]) else cometchat.call_test_accounts(uc["slug"])
    else:
        acc_pair = cometchat.call_test_accounts(uc["slug"])
    li_acc = acc_pair; li_email = li_acc["mobile"][0]
    li_pw = e2e_password(uc)
    login_failed = []
    for plat in ("android", "ios"):
        if shots.get(plat, {}).get("ok") and plat_app_id.get(plat):
            try:
                li = providers.login_and_shot(plat, plat_app_id[plat], li_email, li_pw, str(demo / f"{plat}-loggedin.png"))
            except Exception as e:
                li = {"ok": False, "shot": None, "err": str(e)[:120]}
            shots[f"{plat}-loggedin"] = {"ok": bool(li.get("ok")), "path": li.get("shot")}
            detail = str(li.get("err") or li.get("tail") or "login flow did not reach the logged-in home")[:90]
            print(f"  {plat} login→home: {'✓ logged in' if li.get('ok') else '✗ LOGIN FAILED — ' + detail}")
            if not li.get("ok"):
                login_failed.append(plat)
    # BEHAVIORAL GATE (not just a screenshot): a mobile client that LAUNCHES but can't sign in is broken —
    # backend contract / decode / connectivity. This is the check that would have caught del's iOS Codable
    # crash (login response omitted email) at baseline instead of a human finding it at CP1.
    if login_failed:
        die_gate(f"demo:{uc['slug']} mobile LOGIN failed on {login_failed} — the app launches but can't "
                 f"sign in (backend contract / decode / connectivity). tag=agent")
    # AUTOMATED mobile↔web call matrix (boot-2) — android/ios clients that built OK ring the web peer.
    # Parameterized per use case: the app id + the two call-test accounts (not mkt-hardcoded).
    # A Flutter-unified app's WEB peer is Flutter-web, where CometChat's SDK can't init (shared_preferences
    # MissingPluginException) — so it can never answer. Recording connected=False would read as a calling
    # FAILURE; instead mark the web-peer legs DEFERRED (mobile↔mobile calling is the real Flutter proof, TODO).
    is_flutter_demo = (repo / "app" / "pubspec.yaml").exists() and not (repo / "web").exists()
    if integrated and is_flutter_demo:
        for plat in ("android", "ios"):
            if shots.get(plat, {}).get("ok"):
                mobile_calls[f"{plat}-web-call"] = "deferred-flutter-web-unsupported"
        print("  call-matrix: mobile↔web DEFERRED for Flutter (web peer can't run CometChat); "
              "mobile↔mobile calling is the real proof (TODO)")
    elif integrated:
        web_url = V.get("web_url", "http://localhost:3000")
        acc = acc_pair
        m_email, w_email = acc["mobile"][0], acc["web"][0]
        pw = e2e_password(uc)
        for plat in ("android", "ios"):
            if shots.get(plat, {}).get("ok"):
                for ct in ("voice", "video"):
                    r = verify.run_twoparty_mobile(plat, ct, web_url, str(demo),
                                                   env_file=str(uc_env_file(S, uc)), slug=uc["slug"],
                                                   app_id=plat_app_id.get(plat), mobile_email=m_email,
                                                   web_email=w_email, password=pw, caller_uid=acc["web"][1])
                    mobile_calls[f"{plat}-{ct}"] = bool(r.get("callConnected"))
                    print(f"  call-matrix {plat}↔web {ct}: connected={r.get('callConnected')}")
    print(f"  disk free: {mobile.disk_free_gb()}GB")
    # VISION VERIFY the demo screenshots — each platform must show the REAL app rendered, not a red
    # error screen (crash), a loading spinner (stuck), a blank, or a previous UC's app. This is what
    # catches the failures a raw screenshot silently passed (UC2: iOS go_router red screen, web stuck
    # loading, Android showing the stale mkt app).
    demo_review = {"skipped": True}
    if S.get("verify", {}).get("vision_review", True):
        vs = [{"name": p, "path": shots[p]["path"], "rubric": "app_alive",
               "context": f"{uc['name']} {p} app launch screen"}
              for p in ("web", "android", "ios") if shots.get(p, {}).get("path") and os.path.exists(shots[p]["path"])]
        vs += [{"name": p, "path": shots[p]["path"], "rubric": "feed_loaded",
                "context": f"{uc['name']} {p} — should show real content (backend reached)"}
               for p in ("android-loggedin", "ios-loggedin") if shots.get(p, {}).get("path") and os.path.exists(shots[p]["path"])]
        if vs:
            demo_review = shotreview.review(vs, uc["slug"], S, str(demo / "demo-review.html"))
            for r in demo_review.get("results", []):
                if r.get("correct") is False:
                    shots.setdefault(r["name"], {})["visionAlive"] = False
                    print(f"  ⚠ vision: {r['name']} screen is NOT a healthy render ({r.get('failedChecks')})")
    # Fold MOBILE into the verdict (the eval was web-only): a mobile client that built + launched but
    # connected NO call leg is a real signal. Recorded always; hard-gates only when verify.mobile_gate
    # is set (mobile↔web call automation is acknowledged flaky, so it is advisory by default).
    mobile_built = [k for k in ("android", "ios") if shots.get(k, {}).get("ok")]
    connected_plats = {k.split("-")[0] for k, v in mobile_calls.items() if v}
    mobile_refuted = [p for p in mobile_built if p not in connected_plats] if integrated else []
    res = {"useCase": uc["name"], "slug": uc["slug"], "screenshots": shots, "leftUp": True,
           "integrated": integrated, "mobileCallMatrix": mobile_calls, "mobileRefuted": mobile_refuted,
           "demoReview": demo_review, "webUrl": V.get("web_url", "http://localhost:3000")}
    state.write(S, uc["slug"], "demo", res)
    # Boot-2 gate: the integrated mobile apps MUST have compiled. buildExit is set per platform
    # by build_android/build_ios; a non-zero exit means CometChat integration broke the build.
    if integrated:
        obs.event(S, uc["slug"], "demo", "mobile_verdict", built=mobile_built,
                  connected=sorted(connected_plats), refuted=mobile_refuted)
        broke = [k for k in ("android", "ios")
                 if k in shots and shots[k].get("buildExit") not in (0, None)]
        if broke:
            die_gate(f"demo:{uc['slug']} boot-2 integrated build FAILED for {broke} "
                     f"(rebuild mandatory before CP2) tag=skills")
        if mobile_refuted:
            print(f"  ⚠ mobile call NOT proven for {mobile_refuted} (built but no call leg connected)")
            if S.get("verify", {}).get("mobile_gate", False):
                die_gate(f"demo:{uc['slug']} mobile call not proven for {mobile_refuted} tag=skills")
    oks = [k for k, v in shots.items() if v.get("ok")]
    print(f"OK demo:{uc['slug']} — up for manual test. screenshots: {oks}. Run 'teardown' after approval.")
    return res


def stage_readme(S, uc):
    """Generate + commit the repo-root README.md (codegen reads the real repo). Runs on the
    integration branch so the README ships with the feature. Non-fatal if codegen produces nothing."""
    repo = state.repo_dir(S, uc["slug"]); logs = repo / "_logs"
    # ensure we're on the feature branch (README belongs with the integration, not bare main)
    git(repo, "checkout", "-q", "feature/cometchat-integration")
    r = claude_runner.run_headless(prompts.render_readme(S, uc, str(repo)), settings=S, phase="A",
                                   cwd=repo, model_key="build", label="readme", log_dir=logs)
    readme = repo / "README.md"
    committed = False
    if readme.exists() and readme.stat().st_size > 100:
        git(repo, "add", "README.md")
        code, _ = git(repo, "diff", "--cached", "--quiet")  # nonzero exit => staged changes exist
        if code != 0:
            git(repo, "commit", "-q", "-m", f"docs: README for {uc['name']}")
            committed = True
    res = {"useCase": uc["name"], "slug": uc["slug"], "readmeWritten": readme.exists(),
           "committed": committed, "tail": r["tail"]}
    state.write(S, uc["slug"], "readme", res)
    print(f"OK readme:{uc['slug']} written={readme.exists()} committed={committed}")
    return res


def stage_teardown(S, uc):
    """Cleanly close the demo — docker down -v, uninstall THIS use case's apps + any stale prior-UC
    apps, shut sims/emulator."""
    repo = state.repo_dir(S, uc["slug"])
    td = verify.compose_down(repo) if (repo / "docker-compose.yml").exists() else {"dockerCleanupDone": True}
    # resolve the actual app package(s) for this use case (not the mkt-hardcoded default)
    pkg = None
    for c in prompts.expand_components(uc):
        if c["kind"] in ("mobile", "app", "android", "ios"):
            pkg = providers.resolve_app_id(c["kind"], repo / c["dir"]) or pkg
    stale = mobile.clean_stale_apps(keep_pkg=None)   # also sweep leftover prior-UC apps off the emulator
    md = mobile.teardown_mobile(ios_bundle=pkg, android_pkg=pkg)
    res = {"dockerCleanupDone": td.get("dockerCleanupDone"), "mobileTornDown": md, "staleAppsRemoved": stale}
    state.write(S, uc["slug"], "teardown", res)
    print(f"OK teardown:{uc['slug']} — docker down, sims/emulator shut, apps uninstalled")
    return res


def stage_containerize(S, uc):
    """Generate Dockerfiles + root docker-compose.yml so the baseline can boot (Deskline pattern)."""
    if not gates.baseline(state.read(S, uc["slug"], "build") or {}):
        die_gate(f"containerize needs GATE.baseline:{uc['slug']}")
    repo = state.repo_dir(S, uc["slug"]); logs = repo / "_logs"
    r = claude_runner.run_headless(prompts.render_containerize(S, uc), settings=S, phase="A",
                                   cwd=repo, model_key="build", label="containerize", log_dir=logs)
    compose = (repo / "docker-compose.yml").exists() or (repo / "compose.yaml").exists()
    if compose:
        git(repo, "add", "-A"); git(repo, "commit", "-q", "-m", f"containerize {uc['name']} baseline")
    res = {"useCase": uc["name"], "slug": uc["slug"], "composeCreated": compose, "tail": r["tail"]}
    state.write(S, uc["slug"], "containerize", res)
    if not compose:
        die_gate(f"containerize:{uc['slug']} — no docker-compose.yml produced tag=agent")
    print(f"OK containerize:{uc['slug']} compose ready"); return res


def stage_boot(S, uc):
    if not gates.baseline(state.read(S, uc["slug"], "build") or {}):
        die_gate(f"boot needs GATE.baseline:{uc['slug']}")
    if not gates.containerize(state.read(S, uc["slug"], "containerize") or {}):
        die_gate(f"boot needs GATE.containerize:{uc['slug']} — containerize produced no docker-compose tag=agent")
    repo = state.repo_dir(S, uc["slug"]); V = S["verify"]
    hpaths = V.get("backend_health_paths") or [V.get("backend_health_path", "/health")]
    # Flutter web is served static from build/web — build it on the HOST first (no Docker version drift).
    if (repo / "app" / "pubspec.yaml").exists():
        wb = providers.host_build_flutter_web(repo / "app")
        print(f"  host flutter web build: ok={wb.get('ok')}")
    dockerUp, tail = (verify.compose_up(repo) if (repo / "docker-compose.yml").exists() else (False, "no compose"))
    backend_ok, hp = verify.health_check(V.get("backend_url", "http://localhost:8080"), hpaths,
                                         V["backend_health_timeout_s"]) if dockerUp else (False, None)
    web_ok, _ = verify.health_check(V.get("web_url", "http://localhost:3000"), ["/"], 60) if dockerUp else (False, None)
    web_dir = repo / "web" if (repo / "web").exists() else repo
    smoke = verify.run_e2e(V["e2e"].get("web", ""), web_dir, base_url=V.get("web_url", "http://localhost:3000"))
    login_ok = smoke["passed"] if smoke["ran"] else web_ok  # honest fallback: page-200 if no e2e configured
    td = verify.compose_down(repo) if dockerUp else {"dockerCleanupDone": True}
    res = {"useCase": uc["name"], "ucSlug": uc["slug"], "dockerUp": dockerUp, "emulatorUp": False,
           "servicesHealthy": [{"name": "backend", "status": backend_ok, "healthPath": hp},
                               {"name": "web", "status": web_ok}],
           "allServicesHealthy": bool(backend_ok and web_ok),
           "loginSmokePassed": bool(login_ok), "loginSmokeMethod": "e2e" if smoke["ran"] else "page-200",
           "loginSmokeTail": smoke.get("tail", "")[-1200:],
           "teardownDone": td.get("dockerCleanupDone"), "bootEvidenceTail": tail}
    state.write(S, uc["slug"], "boot", res)
    if not gates.baseline_up(res):
        die_gate(f"baselineUp:{uc['slug']} (healthy={res['allServicesHealthy']}, smoke={res['loginSmokePassed']}) tag=agent")
    print(f"OK boot:{uc['slug']} healthy+smoke"); return res


def stage_push_main(S, uc):
    repo = state.repo_dir(S, uc["slug"])
    secret_scan_or_die(S, uc, repo, "push-main")  # §4.6: never ship a secret to a public repo
    sh("gh", "repo", "create", uc["repo"], "--public")  # idempotent: no-op if exists (use cases are public)
    _, login = sh("gh", "api", "user", "-q", ".login"); owner = login.strip()
    git(repo, "remote", "remove", "origin"); git(repo, "remote", "add", "origin",
        f"https://github.com/{owner}/{uc['repo']}.git")
    code, out = git(repo, "push", "-u", "origin", "main")
    res = {"repo": uc["repo"], "owner": owner, "pushedMain": code == 0, "tail": out[-500:]}
    state.write(S, uc["slug"], "push-main", res)
    if code != 0:  # surface a failed push instead of a silent WARN that reads as 'complete'
        obs.record_failure(S, uc["slug"], "push-main", gate="push", summary=f"push main failed: {out[-160:]}",
                           signals={"exit": code}, evidence=[out[-500:]])
    print(f"{'OK' if code==0 else 'WARN'} push-main:{uc['slug']} -> {owner}/{uc['repo']}"); return res


def stage_integrate(S, uc):
    if not gates.baseline_up(state.read(S, uc["slug"], "boot") or {}):
        die_gate(f"integrate needs GATE.baselineUp:{uc['slug']} — no integrating on a dead baseline")
    load_envfile_into_os(S, uc)  # integration codegen needs the CometChat app creds
    if not os.environ.get("COMETCHAT_APP_ID"):
        die_gate(f"integrate:{uc['slug']} needs COMETCHAT_APP_ID — run provision-app first tag=agent")
    repo = state.repo_dir(S, uc["slug"]); logs = repo / "_logs"
    scoped = bool(os.environ.get("STEP4_ONLY"))
    if scoped:
        # SCOPED (additive) integrate: only some components are being (re)integrated, so we must NOT
        # reset the feature branch to the bare baseline — that would discard the OTHER components'
        # already-integrated (and possibly hand-verified) code. Stay on the feature branch and mutate
        # only the target component's dir; a clean checkout would defeat the whole point of scoping.
        git(repo, "checkout", "-q", "-B", "feature/cometchat-integration")
        ensure_repo(repo)
    else:
        # ROLLBACK: every integrate attempt starts from the KNOWN-GOOD baseline, not a half-mutated tree
        # left by a prior failed attempt (which caused nondeterministic re-runs, duplicate wiring, or a
        # green compile over incoherent code). reset+clean keeps the gitignored injected .env/node_modules.
        git(repo, "checkout", "-q", "main"); git(repo, "checkout", "-q", "-B", "feature/cometchat-integration")
        git(repo, "reset", "--hard", "main"); git(repo, "clean", "-fdq")
        ensure_repo(repo)  # refresh .gitignore on the feature branch so integrate never tracks the cred
        #                    files self-heal writes (.dart_define.json/local.properties) — untracks any too
    comps, worst, reports = _only_filter(prompts.expand_components(uc)), 0, []
    for c in comps:
        cdir = repo / c["dir"]
        # env allowlist: the integrate codegen agent gets APP_ID/REGION/AUTH_KEY but NOT the
        # automation/REST/webhook secrets it has no legitimate use for (injection/exfiltration guard).
        r = claude_runner.run_headless(prompts.render_integrate(S, uc, c), settings=S, phase="B",
                                       cwd=cdir, model_key="integrate", label=f"integrate-{c['name']}",
                                       log_dir=logs, deny_env=secrets.INTEGRATE_DENY_ENV)
        g = verify.build_gate(c["kind"], cdir)
        # SELF-HEAL parity with build: a known compile signature (jdk17/gradle/pod/…) auto-repairs+retries
        healed = []
        if g["buildExitCode"] != 0:
            ctx = {"stage": "integrate", "slug": uc["slug"], "kind": c["kind"], "stack": c["stack"], "repo_dir": repo,
                   "comp_dir": cdir, "mobile_dir": cdir, "env_file": str(uc_env_file(S, uc)), "integrated": True}
            healed = selfheal.heal(ctx, g["outputTail"])
            if healed:
                print(f"  self-heal integrate:{c['name']} → {[h['rule'] for h in healed]}; retrying")
                g = verify.build_gate(c["kind"], cdir, env=ctx.get("env")); g["selfHealed"] = [h["rule"] for h in healed]
        # LAYER 2 — SKILLS CRITIC (concurrent, per-component). An adversarial reviewer reads THIS component's
        # diff + the build/self-heal log and extracts genuine CometChat skills/docs/SDK gaps the builder did
        # NOT self-report, with retraction discipline. Runs even on a CLEAN compile (most gaps are silent —
        # a component that renders but no-ops) and DURING integrate so self-heal can't fix-and-hide.
        if S.get("skills_critic", True):
            sh_ids = ", ".join(h["rule"] for h in healed) or "none"
            try:
                cr = claude_runner.run_headless(
                    prompts.render_skills_critic(S, uc, c, g.get("outputTail", ""), g["buildExitCode"], sh_ids),
                    settings=S, phase="B", cwd=cdir, model_key="critic", label=f"critic-{c['name']}",
                    log_dir=logs, deny_env=secrets.INTEGRATE_DENY_ENV)
                print(f"  skills-critic {c['name']}: agentOk={cr.get('agentOk')} tokens={cr.get('tokens')}")
                obs.event(S, uc["slug"], "integrate", "critic_end", component=c["name"], agentOk=cr.get("agentOk"))
            except Exception as e:
                print(f"  skills-critic {c['name']} skipped: {str(e)[:100]}")
        rep = {"component": c["name"], "kind": c["kind"], "stack": c["stack"],
               "compileExitCode": g["buildExitCode"], "tokens": r["tokens"],
               "hitMaxTurns": r.get("hitMaxTurns"), "isError": r.get("isError"),
               "agentOk": r.get("agentOk"), "terminalReason": r.get("terminalReason"),
               "costUsd": r.get("costUsd"), "tail": g["outputTail"]}
        state.write(S, uc["slug"], f"report-{c['name']}", rep); reports.append(rep)
        obs.event(S, uc["slug"], "integrate", "codegen_end", component=c["name"],
                  compileExit=g["buildExitCode"], agentOk=r.get("agentOk"),
                  hitMaxTurns=r.get("hitMaxTurns"), tokens=r["tokens"], costUsd=r.get("costUsd"))
        worst = max(worst, g["buildExitCode"])  # compile authoritative; agentOk (below) gates truncation
    truncated = [rp["component"] for rp in reports if not rp.get("agentOk", True)]
    # commit ONLY a complete, compiling integration — never a truncated one
    if worst == 0 and not truncated:
        git(repo, "add", "-A"); git(repo, "commit", "-q", "-m", f"CometChat integration {uc['name']}")
    gaps.rebuild(S)
    res = {"useCase": uc["name"], "slug": uc["slug"], "compileExitCode": worst,
           "reports": reports, "truncatedComponents": truncated}
    state.write(S, uc["slug"], "integrate", res)
    if not gates.integrate(res):
        fail_gate(S, uc, "integrate",
                  f"integrate:{uc['slug']} compileExit={worst} truncated={truncated}",
                  {"exit": 2, "hitMaxTurns": bool(truncated),
                   "isError": any(rp.get("isError") for rp in reports)},
                  gate="integrate", evidence=[rp.get("tail", "")[:200] for rp in reports])
    print(f"OK integrate:{uc['slug']} compiled (no truncation)"); return res


def stage_verify(S, uc):
    if not gates.integrate(state.read(S, uc["slug"], "integrate") or {}):
        die_gate(f"verify needs GATE.integrate:{uc['slug']}")
    load_envfile_into_os(S, uc)  # SDK init + compose need the creds
    repo = state.repo_dir(S, uc["slug"]); V = S["verify"]
    web_url = V.get("web_url", "http://localhost:3000")
    (repo / "_demo").mkdir(exist_ok=True); demo_dir = str(repo / "_demo")
    # STEP 1 — re-boot the integrated system; health-check BOTH backend AND web (web was never checked)
    hpaths = V.get("backend_health_paths") or [V.get("backend_health_path", "/health")]
    # Inject THIS use case's OWN CometChat creds into the backend compose env. The integrate code reads
    # env('COMETCHAT_APP_ID') to mint the auth token, but compose passed none → empty token → the app
    # skips CometChat login → the conversation list errors ("Oops") on every client. Routed through
    # preapply so self-heal WITNESSES it as a skills finding (not a silent fix).
    _ce = selfheal.preapply({"stage": "verify", "slug": uc["slug"], "repo_dir": repo,
                             "env_file": str(uc_env_file(S, uc)), "integrated": True})
    if _ce:
        print(f"  verify compose-env self-heal: {[x['rule'] for x in _ce]}")
    # A Flutter-unified app serves web statically from app/build/web — host-build the INTEGRATED web
    # (with CometChat + the semantics hook, empty API_URL → nginx /api proxy) BEFORE compose, else the
    # web container serves the stale baseline build and the chat-receive proof runs against the wrong app.
    if (repo / "app" / "pubspec.yaml").exists() and not (repo / "web").exists():
        wb = providers.host_build_flutter_web(repo / "app", env_file=str(uc_env_file(S, uc)))
        print(f"  verify host flutter web build: ok={wb.get('ok')}")
    dockerUp, boot_tail = (verify.compose_up(repo) if (repo / "docker-compose.yml").exists() else (False, "no compose"))
    backend_ok, _ = verify.health_check(V.get("backend_url", "http://localhost:8080"), hpaths,
                                        V["backend_health_timeout_s"]) if dockerUp else (False, None)
    web_ok, _ = verify.health_check(web_url, ["/"], 60) if dockerUp else (False, None)
    healthy = bool(backend_ok and web_ok)
    obs.event(S, uc["slug"], "verify", "reboot", dockerUp=dockerUp, backendOk=backend_ok, webOk=web_ok)
    # A system that won't boot is INFRA/agent — NOT a skills gap. Fail with the right cause instead of
    # running e2e that will 'refute' and mislabel skills (the ledger-poisoning misattribution).
    if not healthy:
        if dockerUp:
            verify.compose_down(repo)
        fail_gate(S, uc, "verify",
                  f"verify:{uc['slug']} integrated system did not boot healthy (backend={backend_ok} web={web_ok})",
                  {"dockerUp": dockerUp, "allServicesHealthy": False}, gate="integratedUp",
                  evidence=[str(boot_tail)[:300]])
    # STEP 2 — resolve the two chat-test parties from the app's OWN demo accounts (uc.chatPair),
    # discover their CometChat uid via app login, and seed a conversation between them. No dependency
    # on a chat-a/chat-b baseline seed (which drifts) — it uses accounts the app definitely has.
    password = e2e_password(uc)
    pair = cometchat.seed_and_resolve_pair(str(uc_env_file(S, uc)), uc, V.get("backend_url", "http://localhost:8080"), password)
    obs.event(S, uc["slug"], "verify", "chat_pair", mode=pair.get("mode"), ok=pair.get("ok"),
              web=pair["web"][0], mobile=pair["mobile"][0])
    if not pair.get("ok"):
        if dockerUp:
            verify.compose_down(repo)
        die_gate(f"verify:{uc['slug']} could not resolve/seed the chat-test pair ({pair.get('mode')}) — "
                 f"check chatPair emails exist in the app seed: {pair.get('loginError') or 'seed send failed'} tag=setup")
    seed = {"ok": True}
    a_email, b_email = pair["web"][0], pair["mobile"][0]   # A = receiver, B = sender
    recv_uid, send_uid = pair["web"][1], pair["mobile"][1]
    submit = uc.get("e2eSubmit", "Sign In")
    nonce_base = f"rx-{uc['slug']}-{int(time.time())}"
    # The WEB-CLIENT SHAPE picks the e2e path: a Node web/ dir → browser DOM e2e; a Flutter-unified app
    # (no web/, served static from app/build/web) → the flt-semantics tree; native-only → no web e2e.
    has_web = (repo / "web").exists()
    is_flutter = (repo / "app" / "pubspec.yaml").exists() and not has_web
    if has_web:
        # ---- Node web: cross-party receive (DOM) + single-browser SDK signal + two-party call ----
        chat, chat_attempts = {}, []
        for attempt in range(2):
            chat = verify.run_twoparty_chat(repo, web_url, demo_dir, a_email, b_email, password, f"{nonce_base}-{attempt}")
            chat_attempts.append({"received": bool(chat.get("received")), "error": chat.get("error")})
            if chat.get("received") or chat.get("error"):
                break
        chat_ok, chat_harness = bool(chat.get("received")), bool(chat.get("error"))
        shot = str(repo / "_demo" / "web-call.png")
        e2e = verify.run_chatcall_web(repo, a_email, password, web_url, shot)
        sdk_ok = bool(e2e.get("sdkReady"))
        matrix = verify.run_twoparty_web(repo, web_url, demo_dir, a_email, b_email, password,
                                         env_file=str(uc_env_file(S, uc)), slug=uc["slug"])
        twoparty_ok = bool(matrix.get("ok"))
        call_ok = twoparty_ok
        call_matrix = {"web-web": {"voice": bool(matrix.get("voice", {}).get("callWorks")),
                                   "video": bool(matrix.get("video", {}).get("callWorks")), "mode": "automated"},
                       "android-web": {"mode": "manual-demo", "note": "verified in demo boot-2 (CP2)"},
                       "ios-web": {"mode": "manual-demo", "note": "verified in demo boot-2 (CP2)"}}
    elif is_flutter:
        # ---- Flutter-unified: prove chat RECEIVE on the MOBILE client (android). CometChat's SDK does
        # NOT initialise on Flutter web (shared_preferences MissingPluginException → the Conversations
        # component shows "Oops"), so a web chat proof can never pass for a real integration — it is
        # DEFERRED like Flutter-web calling, never faked. A logs in on-device, a peer REST-sends a unique
        # nonce, and A's mobile UI must render it. ----
        cfg = cometchat._cfg(str(uc_env_file(S, uc)))
        shot = str(repo / "_demo" / "chat-receive.png")
        api_android = S["verify"].get("api_android", "http://10.0.2.2:8080")
        b_name = pair["mobile"][2] if len(pair["mobile"]) > 2 else ""   # sender's display name (thread title)
        chat, chat_attempts = {}, []
        for attempt in range(2):
            chat = verify.run_flutter_chat_receive_mobile(repo, api_android, str(uc_env_file(S, uc)), cfg,
                                                          a_email, send_uid, recv_uid,
                                                          f"{nonce_base}-{attempt}", shot,
                                                          sender_name=b_name, submit=submit, settings=S)
            chat_attempts.append({"received": bool(chat.get("received")), "built": chat.get("built"),
                                  "error": chat.get("error")})
            if chat.get("received") or not chat.get("built"):   # a build/install failure won't fix on retry
                break
        chat_ok = bool(chat.get("received"))
        chat_harness = bool(chat.get("error")) and not chat.get("built")
        sdk_ok = bool(chat.get("sdkReady") or chat.get("received"))
        e2e = chat
        matrix, twoparty_ok, call_ok = {"mode": "deferred-flutter-demo"}, None, None
        call_matrix = {"web-web": {"mode": "deferred-flutter-web-unsupported",
                                   "note": "CometChat Flutter UIKit does not init on web; calling+chat proven on mobile"},
                       "android-web": {"mode": "manual-demo"}, "ios-web": {"mode": "manual-demo"}}
    else:
        # ---- native-only web (unreachable for the current 10 archetypes) — rely on demo boot-2 ----
        shot = str(repo / "_demo" / "web-call.png")
        chat, chat_attempts, e2e = {"error": "no web e2e for this archetype"}, [], {}
        chat_ok, chat_harness, sdk_ok = False, True, bool(seed.get("ok"))
        matrix, twoparty_ok, call_ok = {"mode": "deferred-demo"}, None, None
        call_matrix = {"web-web": {"mode": "deferred-demo"}, "android-web": {"mode": "manual-demo"},
                       "ios-web": {"mode": "manual-demo"}}
    # STEP 6 — AI moderation probe (reads the DELIVERED copy now, so masking can actually be observed)
    moderation = cometchat.check_moderation(str(uc_env_file(S, uc)), uc["slug"])
    # STEP 7 — VISION review, now with TEETH on the call-critical rubrics (verify.vision_gate).
    shot_review = {"skipped": True}
    if S.get("verify", {}).get("vision_review", True):
        # chat-receive thread is reviewed on EVERY web shape. The CALL rubrics apply only to the Node-web
        # call path — Flutter calling is deferred to the demo boot-2 matrix, so reviewing a Flutter run's
        # chat screenshot against an ongoing_call rubric is a false refute (it isn't a call screen).
        candidates = [("chat-receive", str(repo / "_demo" / "chat-receive.png"), "chat_thread", "cross-party received msg")]
        if not is_flutter:
            candidates.append(("web-call", shot, "ongoing_call", "web ongoing call"))
            for tag in ("voice", "video"):
                candidates += [(f"callee-ringing-{tag}", str(repo / "_demo" / f"callee-ringing-{tag}.png"), "incoming_ring", f"web {tag} incoming"),
                               (f"callee-ongoing-{tag}", str(repo / "_demo" / f"callee-ongoing-{tag}.png"), "ongoing_call", f"web {tag} ongoing")]
        shots = [{"name": n, "path": p, "rubric": rb, "context": cx} for n, p, rb, cx in candidates if os.path.exists(p)]
        if shots:
            shot_review = shotreview.review(shots, uc["slug"], S, str(repo / "_demo" / "shot-review.html"))
    # Vision TEETH apply ONLY to rubrics an automated browser can actually render. Two-party WebRTC
    # media cannot be negotiated headless — the caller stays stuck at the "Calling…" modal and the
    # callee renders blank — so the web CALL rubrics (ongoing_call / incoming_ring) are structurally
    # unprovable via screenshot: a blank callee shot is indistinguishable from a genuinely broken call
    # UI, so the check has zero discriminating power here and only ever produces false refutes. Those
    # shots stay in the gallery + get triaged to notes for a human to eyeball, but they do NOT refute.
    # The call CONNECTION is proven by machine evidence (callConnect / twoPartyWeb signaling), and the
    # call UI by the css-var self-heal + the native↔native live-call matrix. chat_thread IS renderable
    # headless, so it keeps its teeth. Mirrors the Flutter call-rubric carve-out above.
    GATING_RUBRICS = {"chat_thread"}
    vision_results = shot_review.get("results", []) or []
    vision_ran = shot_review.get("allCorrect") is not None
    vision_any_fail = any(r.get("correct") is False for r in vision_results)
    vision_critical_fail = any(r.get("correct") is False and r.get("rubric") in GATING_RUBRICS
                               for r in vision_results)
    vision_gate = S.get("verify", {}).get("vision_gate", True)
    # SCORECARD — the verdict is a pure function of cross-party MACHINE evidence, not DOM shape.
    scorecard = {"sdkInit": sdk_ok, "chatReceive": chat_ok,
                 "callConnect": ("deferred-demo" if is_flutter else call_ok),
                 "twoPartyWeb": ("deferred-demo" if is_flutter else twoparty_ok),
                 "moderationActive": bool(moderation.get("active")),
                 "visionOk": (None if not vision_ran else not vision_critical_fail)}
    integratedUp = bool(dockerUp and healthy and sdk_ok)
    # Flutter web calling is proven in demo boot-2 (mobile matrix), not at verify — so it is NOT part
    # of the verify refute; verify proves Flutter chat-receive + SDK-init.
    refuted = not (sdk_ok and chat_ok and (True if is_flutter else bool(call_ok)))
    if vision_gate and vision_critical_fail:
        refuted = True
    td = verify.compose_down(repo) if dockerUp else {"dockerCleanupDone": True}
    easeScore = (4 if chat_ok else 1) if is_flutter else (5 if (chat_ok and call_ok) else (3 if chat_ok else 1))
    res = {"useCase": uc["name"], "slug": uc["slug"], "dockerUp": dockerUp, "emulatorUp": False,
           "allServicesHealthy": healthy, "sdkInitOk": sdk_ok, "integratedUp": integratedUp,
           "cometchatUsersSeeded": 2 if seed.get("ok") else 0,
           "chatWorks": chat_ok, "callWorks": call_ok, "refuted": refuted, "scorecard": scorecard,
           "chatAttempts": chat_attempts, "chatHarnessError": chat_harness,
           "callMatrix": call_matrix, "twoPartyWebWorks": twoparty_ok,
           "moderation": {"active": moderation.get("active"), "detail": moderation.get("note"),
                          "masked": moderation.get("masked"), "blocked": moderation.get("blocked")},
           "reason": ("chat(receive)+sdk proven; call→demo boot-2" if is_flutter else "chat(receive)+call(2party)+sdk proven")
                     if not refuted else f"refuted: sdk={sdk_ok} chatRx={chat_ok} call={call_ok} vision={scorecard['visionOk']}",
           "easeScore": easeScore,
           "shotReview": {"allCorrect": shot_review.get("allCorrect"), "anyChanged": shot_review.get("anyChanged"),
                          "gallery": shot_review.get("gallery"), "results": shot_review.get("results")},
           "dockerCleanupDone": td.get("dockerCleanupDone"), "e2e": e2e, "callScreenshot": shot}
    state.write(S, uc["slug"], "verify", res)
    obs.event(S, uc["slug"], "verify", "verdict", refuted=refuted, sdk=sdk_ok, chatRx=chat_ok,
              call=call_ok, twoparty=twoparty_ok, vision=scorecard["visionOk"])
    # Triage notes — routed by cause; harness/setup NEVER pollute the skills gaps ledger.
    notes = []
    if chat_harness:
        notes.append(f"[harness] cross-party chat proof did not run cleanly — {str(chat)[:300]}")
    elif not chat_ok:
        notes.append(f"[integration] cross-party message NOT received (real-time socket) — {chat_attempts}")
    if not is_flutter and not twoparty_ok:
        notes.append(f"[coverage] two-party web↔web call matrix incomplete — {str(matrix)[:250]}")
    if not moderation.get("active"):
        notes.append(f"[setup] AI moderation not observed — {moderation.get('note')} "
                     f"(enable the moderation/data-masking extension in the CometChat dashboard)")
    if vision_any_fail:
        bad = [f"{r['name']}({','.join(r.get('failedChecks', []))})" for r in vision_results if r.get("correct") is False]
        gating_bad = [r["name"] for r in vision_results if r.get("correct") is False and r.get("rubric") in GATING_RUBRICS]
        if gating_bad:
            notes.append(f"[visual] Claude-vision flagged (GATING): {', '.join(bad)} — see gallery {shot_review.get('gallery')}")
        else:
            notes.append(f"[env] web CALL screens unrenderable headless — two-party WebRTC media can't be negotiated "
                         f"in an automated browser (caller stuck at 'Calling…', callee blank): {', '.join(bad)}. Call "
                         f"CONNECTION proven by machine evidence (callConnect/twoParty) + native↔native live matrix; "
                         f"these shots are ADVISORY. See gallery {shot_review.get('gallery')}")
    if notes:
        notes_dir = os.path.join(os.path.dirname(os.path.expanduser(S["gaps_dir"])), "pipeline-notes")
        os.makedirs(notes_dir, exist_ok=True)
        with open(os.path.join(notes_dir, f"{uc['slug']}.md"), "a") as f:
            f.write(f"\n### auto-recorded verify triage ({uc['slug']})\n" + "\n".join(f"- {n}" for n in notes) + "\n")
    if not gates.verify(res):
        err = str(chat.get("error", "")) + str(e2e.get("error", "")) + str(e2e.get("pageErrors", ""))
        fail_gate(S, uc, "verify",
                  f"verify:{uc['slug']} refuted (sdk={sdk_ok} chatRx={chat_ok} call={call_ok} vision={scorecard['visionOk']})",
                  {"dockerUp": dockerUp, "allServicesHealthy": healthy, "exit": 2}, gate="verify", err=err,
                  evidence=[shot, shot_review.get("gallery", "")])
    print(f"OK verify:{uc['slug']} sdk={sdk_ok} chatRx={chat_ok} call={'demo-boot2' if is_flutter else call_ok} "
          f"mod={moderation.get('active')} vision={scorecard['visionOk']} ease={easeScore}"); return res


def stage_push_branch(S, uc):
    if not gates.verify(state.read(S, uc["slug"], "verify") or {}):
        die_gate(f"push-branch needs GATE.verify:{uc['slug']}")
    repo = state.repo_dir(S, uc["slug"])
    secret_scan_or_die(S, uc, repo, "push-branch")  # §4.6: scan the integration branch before it ships
    code, out = git(repo, "push", "-u", "origin", "feature/cometchat-integration")
    res = {"pushedBranch": code == 0, "tail": out[-500:]}
    state.write(S, uc["slug"], "push-branch", res)
    if code != 0:
        obs.record_failure(S, uc["slug"], "push-branch", gate="push", summary=f"push branch failed: {out[-160:]}",
                           signals={"exit": code}, evidence=[out[-500:]])
    print(f"{'OK' if code==0 else 'WARN'} push-branch:{uc['slug']} — use case complete"); return res


STAGES = {"preflight": stage_preflight, "provision-app": stage_provision,
          "build": stage_build, "containerize": stage_containerize, "boot": stage_boot,
          "demo": stage_demo, "teardown": stage_teardown,
          "push-main": stage_push_main, "integrate": stage_integrate,
          "verify": stage_verify, "readme": stage_readme, "push-branch": stage_push_branch}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--use-case", required=True)
    ap.add_argument("--stage", required=True, choices=list(STAGES))
    ap.add_argument("--settings", default="settings.json")
    args = ap.parse_args()
    S = load(args.settings)
    augment_path(S)  # make self-installed tools findable in every stage
    ucs = {u["slug"]: u for u in load("use_cases.json")["use_cases"]}
    if args.use_case not in ucs:
        print(f"unknown use case {args.use_case}", file=sys.stderr); sys.exit(3)
    uc = ucs[args.use_case]; slug = uc["slug"]
    obs.run_id()  # mint/read the correlation id for this stage process
    obs.event(S, slug, args.stage, "stage_start")
    t0 = time.time()
    try:
        STAGES[args.stage](S, uc)
        obs.event(S, slug, args.stage, "stage_end", exit=0, durationS=round(time.time() - t0, 1))
    except SystemExit as e:
        code = e.code if isinstance(e.code, int) else 2
        obs.event(S, slug, args.stage, "stage_end", exit=code, durationS=round(time.time() - t0, 1))
        raise
    except Exception as e:
        import traceback; tb = traceback.format_exc(); traceback.print_exc()
        obs.record_failure(S, slug, args.stage, gate=args.stage, summary=str(e)[:200],
                           signals={"exit": 3, "isError": True}, err=tb)
        obs.event(S, slug, args.stage, "stage_error", exit=3, err=str(e)[:200])
        print(f"STAGE-ERROR: {e}", file=sys.stderr); sys.exit(3)


if __name__ == "__main__":
    main()
