#!/usr/bin/env python3
"""run_usecase.py — deterministic stage worker for the STEP4 hybrid pipeline.

One stage per invocation; exits after each. Holds NO state between calls — all
state is on disk (git repo in work_root/<slug>/, JSON in _reports/ + pipeline-state/).
The ONLY LLM calls are the per-component `claude -p` codegen + one judge; every
gate is deterministic Python. Never blocks on input() — the conductor (session or
batch_runner.py) sequences stages and holds the human checkpoints.

Stages:  build → boot → push-main → integrate → verify → push-branch
Exit:    0 ok+gate-pass · 2 gate-fail (conductor halts) · 3 stage error

Usage:   python3 run_usecase.py --use-case mkt --stage build
"""
from __future__ import annotations
import argparse, json, os, subprocess, sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(__file__))
import time  # noqa: E402
from lib import claude_runner, gates, prompts, state, verify, gaps, readiness, mobile, cometchat, shotreview, selfheal, providers  # noqa: E402

HERE = Path(__file__).resolve().parent
AUTOMATE_ROOT = HERE.parent
ENV_FILE = AUTOMATE_ROOT / ".env.pipeline"


def load_envfile_into_os():
    """Load .env.pipeline into os.environ so codegen/provision agents see the creds."""
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                if v:
                    os.environ[k.strip()] = v.strip()
    os.environ["COMETCHAT_ENV_FILE"] = str(ENV_FILE)


def load(name):
    return json.loads((HERE / "config" / name).read_text())


def git(repo: Path, *args) -> tuple[int, str]:
    cmd = ["git", "-c", "user.email=pipeline@step4.local", "-c", "user.name=step4-pipeline", *args]
    p = subprocess.run(cmd, cwd=str(repo), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return p.returncode, p.stdout


# Written at repo init so `git add -A` NEVER tracks deps/build junk/secrets. Without this the baseline
# codegen commits node_modules + .venv + build outputs (UC1 hit 83k tracked files / 337M, ~95% junk)
# and every rebuild churns thousands of artifacts. Keep .example templates; real .env is build-time only.
GITIGNORE = """\
# Dependencies
node_modules/

# Python virtualenv
.venv/
venv/

# Native build outputs (regenerated by expo prebuild + gradle/xcode)
**/build/
.gradle/
android/.gradle/
android/app/build/
ios/build/
ios/Pods/
**/DerivedData/
**/.cxx/
.expo/
.kotlin/

# Web build output
.next/
out/

# Secrets — build-time creds are injected by the pipeline (mobile.write_cometchat_env). Commit only .example.
.env
!.env.example

# Pipeline / demo artifacts (not app source)
_demo/
_logs/
_reports/
pipeline-state/
test-results/

# Ad-hoc e2e scripts copied into web/ at runtime
web/_*.mjs

# Python bytecode / OS cruft
__pycache__/
*.pyc
.DS_Store
*.log
"""


def ensure_repo(repo: Path) -> None:
    """Init the repo on `main` AND write .gitignore before any `git add -A` runs, so no use case
    ever commits node_modules/.venv/build artifacts/secrets. Idempotent — safe to call repeatedly.
    For a pre-existing repo that already tracked junk (e.g. re-run), untrack whatever the fresh
    .gitignore now excludes (files stay on disk; only the index is cleaned)."""
    fresh = not (repo / ".git").exists()
    if fresh:
        git(repo, "init", "-q"); git(repo, "checkout", "-q", "-b", "main")
    gi = repo / ".gitignore"
    if not gi.exists() or "node_modules/" not in gi.read_text():
        gi.write_text(GITIGNORE)
    if not fresh:  # existing repo — drop any tracked files the .gitignore now ignores
        code, tracked = git(repo, "ls-files", "-ci", "--exclude-standard")
        if code == 0 and tracked.strip():
            sh_shell(f"cd {repo!s} && git ls-files -ci --exclude-standard -z | "
                     f"xargs -0 git rm -r --cached --quiet 2>/dev/null || true")


def sh(*args, cwd=None, timeout=600) -> tuple[int, str]:
    p = subprocess.run(list(args), cwd=cwd, text=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return p.returncode, p.stdout


def sh_shell(cmd, timeout=1200) -> tuple[int, str]:
    p = subprocess.run(cmd, shell=True, text=True, timeout=timeout,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return p.returncode, p.stdout


def augment_path(S):
    """Make self-installed tools (maestro, android) findable by later stages."""
    import shutil as _sh
    for p in S.get("bootstrap", {}).get("extra_path", []):
        pe = os.path.expanduser(p)
        if pe not in os.environ.get("PATH", ""):
            os.environ["PATH"] = pe + os.pathsep + os.environ.get("PATH", "")
    return _sh


def bootstrap_tools(S) -> dict:
    """Idempotent Phase-0 installs — only run when a tool is actually missing."""
    import shutil
    b = S.get("bootstrap", {}); res = {}
    have_maestro = shutil.which("maestro") or Path(os.path.expanduser("~/.maestro/bin/maestro")).exists()
    if not have_maestro and b.get("maestro_install"):
        code, _ = sh_shell(b["maestro_install"]); res["maestro"] = (code == 0)
    else:
        res["maestro"] = bool(have_maestro)
    # playwright browsers (global cache); the @playwright/test pkg is added per-web-project by the coder
    if b.get("playwright_install"):
        code, _ = sh_shell(b["playwright_install"]); res["playwright"] = (code == 0)
    return res


def die_gate(msg):
    print(f"GATE-FAIL: {msg}", file=sys.stderr); sys.exit(2)


# ===================== STAGES =====================
def stage_preflight(S, uc):
    """Phase 0 — initialise + stack-readiness gate + generate the spec-pin (req:baseline).
    No codegen tokens are spent past here unless this use case's stacks are actually buildable."""
    comps = prompts.expand_components(uc)
    rd = readiness.check(uc, comps, need_docker=True)
    # self-provision the e2e toolchain (installs only what's missing) so verify isn't blocked later
    boot_tools = bootstrap_tools(S)
    # initialise workspace + git
    repo = state.repo_dir(S, uc["slug"]); repo.mkdir(parents=True, exist_ok=True)
    ensure_repo(repo)  # init on main + write .gitignore BEFORE any codegen/add can track junk
    # generate the spec-pin if missing (this is "requirements build once implementation starts")
    req_file = HERE / "requirements" / f"{uc['slug']}.md"
    spec_generated = req_file.exists()
    if rd["ready"] and not spec_generated:
        req_file.parent.mkdir(parents=True, exist_ok=True)
        r = claude_runner.run_headless(prompts.render_requirements(S, uc), settings=S, phase="A",
                                       cwd=HERE, model_key="spec", label=f"spec-{uc['slug']}",
                                       log_dir=repo / "_logs")
        spec_generated = req_file.exists() and req_file.stat().st_size > 200
    res = {"useCase": uc["name"], "slug": uc["slug"], "ready": rd["ready"], "missing": rd["missing"],
           "byComponent": rd["byComponent"], "workspaceInit": (repo / ".git").exists(),
           "e2eTools": boot_tools, "specGenerated": spec_generated, "specFile": str(req_file)}
    state.write(S, uc["slug"], "preflight", res)
    if not rd["ready"]:
        die_gate(f"preflight:{uc['slug']} not build-ready — missing {rd['missing']} tag=agent")
    print(f"OK preflight:{uc['slug']} ready; spec={'yes' if spec_generated else 'PENDING'}"); return res


def stage_provision(S, uc):
    """One-time — use automation keys + docs-mcp to create/configure the shared app and fill creds.
    Idempotent: if COMETCHAT_APP_ID is already set, no-op."""
    load_envfile_into_os()
    if os.environ.get("COMETCHAT_APP_ID"):
        res = {"appIdSet": True, "skipped": "already provisioned"}
        state.write(S, uc["slug"], "provision-app", res)
        print("OK provision-app: already set (no-op)"); return res
    repo = state.repo_dir(S, uc["slug"])
    r = claude_runner.run_headless(prompts.render_provision(S, uc), settings=S, phase="B",
                                   cwd=AUTOMATE_ROOT, model_key="provision", label="provision-app",
                                   log_dir=repo / "_logs")
    load_envfile_into_os()  # re-read — the agent should have filled it
    app_set = bool(os.environ.get("COMETCHAT_APP_ID"))
    res = {"appIdSet": app_set, "exitCode": r["exitCode"], "tail": r["tail"]}
    state.write(S, uc["slug"], "provision-app", res)
    if not app_set:
        die_gate("provision-app: APP_ID not set — check COMETCHAT_DASHBOARD_CHECKLIST.md; provisioning residue is a finding tag=docs-mcp")
    print("OK provision-app: app created + creds written"); return res


def stage_build(S, uc):
    repo = state.repo_dir(S, uc["slug"]); repo.mkdir(parents=True, exist_ok=True)
    logs = repo / "_logs"
    ensure_repo(repo)  # init on main + write .gitignore BEFORE any codegen/add can track junk
    comps, worst, runs = prompts.expand_components(uc), 0, []
    for c in comps:
        cdir = repo / c["dir"]
        r = claude_runner.run_headless(prompts.render_build(S, uc, c), settings=S, phase="A",
                                       cwd=cdir, model_key="build", label=f"build-{c['name']}", log_dir=logs)
        g = verify.build_gate(c["kind"], cdir)
        # SELF-HEAL: if the gate failed with a known UC1 signature, auto-repair + retry once — no human.
        if g["buildExitCode"] != 0:
            healed = selfheal.heal({"stage": "build", "kind": c["kind"], "stack": c["stack"],
                                    "repo_dir": repo, "comp_dir": cdir, "mobile_dir": cdir,
                                    "env_file": str(ENV_FILE), "integrated": False}, g["outputTail"])
            if healed:
                print(f"  self-heal build:{c['name']} → {[h['rule'] for h in healed]}; retrying")
                g = verify.build_gate(c["kind"], cdir); g["selfHealed"] = [h["rule"] for h in healed]
        runs.append({**c, **r, **g}); worst = max(worst, g["buildExitCode"])  # compile is authoritative, not agent exit
    sha = ""
    if worst == 0:
        git(repo, "add", "-A"); git(repo, "commit", "-q", "-m", f"baseline {uc['name']} (no CometChat)")
        _, sha = git(repo, "rev-parse", "HEAD"); sha = sha.strip()
    res = {"useCase": uc["name"], "slug": uc["slug"], "stack": uc["archetype"],
           "buildExitCode": worst, "committedSha": sha,
           "components": runs, "outputTail": (runs[-1]["outputTail"] if runs else "")}
    state.write(S, uc["slug"], "build", res)
    if not gates.baseline(res):
        die_gate(f"baseline:{uc['slug']} (buildExit={worst}, sha={'yes' if sha else 'no'}) tag=agent")
    print(f"OK build:{uc['slug']} sha={sha[:9]}"); return res


def _web_shot(repo, out_png) -> bool:
    """Screenshot the served web app (root; whatever renders — login or home)."""
    web = repo / "web"
    if not web.exists():
        return False
    script = web / "_shot.mjs"
    script.write_text(
        "import { chromium } from '@playwright/test'\n"
        "const b = await chromium.launch()\n"
        "const p = await b.newPage({ viewport: { width: 1280, height: 900 } })\n"
        "await p.goto('http://localhost:3000/', { waitUntil: 'networkidle' }).catch(()=>{})\n"
        "await p.waitForTimeout(2000)\n"
        f"await p.screenshot({{ path: '{out_png}', fullPage: false }})\n"
        "await b.close()\n")
    code, _ = sh("node", str(script), cwd=str(web), timeout=120)
    script.unlink(missing_ok=True)
    return code == 0 and Path(out_png).exists()


def stage_demo(S, uc):
    """MANUAL-VERIFY: boot web + Android + iOS, screenshot each, and LEAVE EVERYTHING UP
    for hands-on testing. Cleanly torn down by stage_teardown after the human approves.

    Boot-2 (post-integrate) MANDATORY rebuild: stage_demo always does a fresh
    prebuild_clean → gradle/xcode release build, so the apps under manual test are built
    from the CURRENT working tree. When integration has run, we additionally (a) assert the
    tree is on feature/cometchat-integration and (b) GATE on the mobile build compiling — a
    broken integrated build must not silently present stale baseline apps at CP2."""
    repo = state.repo_dir(S, uc["slug"]); V = S["verify"]
    demo = repo / "_demo"; demo.mkdir(exist_ok=True)
    kinds = {c["kind"] for c in prompts.expand_components(uc)}
    integrated = bool(state.read(S, uc["slug"], "integrate"))  # boot-2 iff integrate has run
    if integrated:
        _, branch = git(repo, "rev-parse", "--abbrev-ref", "HEAD")
        branch = branch.strip()
        print(f"boot-2 (integrated): rebuilding apps from branch '{branch}'")
        if branch != "feature/cometchat-integration":
            die_gate(f"demo:{uc['slug']} boot-2 must be on feature/cometchat-integration, on '{branch}' tag=agent")
    shots = {}
    # 1. web + backend via docker — leave up
    if (repo / "docker-compose.yml").exists():
        up, _ = verify.compose_up(repo)
        hpaths = V.get("backend_health_paths") or ["/health"]
        verify.health_check(V.get("backend_url", "http://localhost:8080"), hpaths, V["backend_health_timeout_s"])
        if "web" in kinds:
            p = str(demo / "web.png")
            shots["web"] = {"ok": _web_shot(repo, p), "path": p}
    # 2. mobile / native clients — dispatch to the STACK PROVIDER per component (RN / Flutter /
    #    native Android / native iOS). Each provider self-heals (cleartext + creds), builds, installs,
    #    launches and screenshots — the demo stage is no longer RN-only.
    mobile_calls = {}; plat_app_id = {}
    api_a = V.get("api_android", "http://10.0.2.2:8080/api")   # android emulator → host
    api_i = V.get("api_ios", "http://localhost:8080/api")      # ios simulator → localhost
    for c in prompts.expand_components(uc):
        if c["kind"] not in ("mobile", "app", "android", "ios"):
            continue
        prov = providers.mobile_provider(c["kind"], c["stack"])
        if not prov:
            shots[c["name"]] = {"ok": False, "note": f"no demo provider for {c['kind']}/{c['stack']}"}
            continue
        print(f"demo provider [{prov.family}] for {c['name']} ({c['stack']})…")
        ctx = {"app_dir": repo / c["dir"], "repo_dir": repo, "demo_dir": demo,
               "kind": c["kind"], "stack": c["stack"], "api_android": api_a, "api_ios": api_i,
               "api_web": "/api", "integrated": integrated, "env_file": str(ENV_FILE), "settings": S}
        aid = providers.resolve_app_id(c["kind"], repo / c["dir"])
        for plat, shot in prov.demo(ctx).items():   # android / ios / web
            shots[plat] = shot
            if plat in ("android", "ios") and aid:
                plat_app_id[plat] = aid             # per-UC package/bundle for the Maestro flows
    # AUTOMATED mobile↔web call matrix (boot-2) — android/ios clients that built OK ring the web peer.
    # Parameterized per use case: the app id + the two call-test accounts (not mkt-hardcoded).
    if integrated:
        web_url = V.get("web_url", "http://localhost:3000")
        acc = cometchat.call_test_accounts(uc["slug"])
        m_email, w_email = acc["mobile"][0], acc["web"][0]
        pw = uc.get("e2ePassword", "Mkt@seed2026!")
        for plat in ("android", "ios"):
            if shots.get(plat, {}).get("ok"):
                for ct in ("voice", "video"):
                    r = verify.run_twoparty_mobile(plat, ct, web_url, str(demo),
                                                   env_file=str(ENV_FILE), slug=uc["slug"],
                                                   app_id=plat_app_id.get(plat), mobile_email=m_email,
                                                   web_email=w_email, password=pw)
                    mobile_calls[f"{plat}-{ct}"] = bool(r.get("callConnected"))
                    print(f"  call-matrix {plat}↔web {ct}: connected={r.get('callConnected')}")
    print(f"  disk free: {mobile.disk_free_gb()}GB")
    res = {"useCase": uc["name"], "slug": uc["slug"], "screenshots": shots, "leftUp": True,
           "integrated": integrated, "mobileCallMatrix": mobile_calls,
           "webUrl": V.get("web_url", "http://localhost:3000")}
    state.write(S, uc["slug"], "demo", res)
    # Boot-2 gate: the integrated mobile apps MUST have compiled. buildExit is set per platform
    # by build_android/build_ios; a non-zero exit means CometChat integration broke the build.
    if integrated:
        broke = [k for k in ("android", "ios")
                 if k in shots and shots[k].get("buildExit") not in (0, None)]
        if broke:
            die_gate(f"demo:{uc['slug']} boot-2 integrated build FAILED for {broke} "
                     f"(rebuild mandatory before CP2) tag=skills")
    oks = [k for k, v in shots.items() if v.get("ok")]
    print(f"OK demo:{uc['slug']} — up for manual test. screenshots: {oks}. Run 'teardown' after approval.")
    return res


def stage_teardown(S, uc):
    """Cleanly close the demo — docker down -v, uninstall mobile apps, shut sims/emulator."""
    repo = state.repo_dir(S, uc["slug"])
    td = verify.compose_down(repo) if (repo / "docker-compose.yml").exists() else {"dockerCleanupDone": True}
    md = mobile.teardown_mobile("com.mkt.mobile", "com.mkt.mobile")  # bundle/pkg from app.json
    res = {"dockerCleanupDone": td.get("dockerCleanupDone"), "mobileTornDown": md}
    state.write(S, uc["slug"], "teardown", res)
    print(f"OK teardown:{uc['slug']} — docker down, sims/emulator shut, apps uninstalled")
    return res


def stage_containerize(S, uc):
    """Generate Dockerfiles + root docker-compose.yml so the baseline can boot (Deskline pattern)."""
    if not gates.baseline(state.read(S, uc["slug"], "build") or {}):
        die_gate(f"containerize needs GATE.baseline:{uc['slug']}")
    repo = state.repo_dir(S, uc["slug"]); logs = repo / "_logs"
    r = claude_runner.run_headless(prompts.render_containerize(S, uc), settings=S, phase="A",
                                   cwd=repo, model_key="build", label="containerize", log_dir=logs)
    compose = (repo / "docker-compose.yml").exists() or (repo / "compose.yaml").exists()
    if compose:
        git(repo, "add", "-A"); git(repo, "commit", "-q", "-m", f"containerize {uc['name']} baseline")
    res = {"useCase": uc["name"], "slug": uc["slug"], "composeCreated": compose, "tail": r["tail"]}
    state.write(S, uc["slug"], "containerize", res)
    if not compose:
        die_gate(f"containerize:{uc['slug']} — no docker-compose.yml produced tag=agent")
    print(f"OK containerize:{uc['slug']} compose ready"); return res


def stage_boot(S, uc):
    if not gates.baseline(state.read(S, uc["slug"], "build") or {}):
        die_gate(f"boot needs GATE.baseline:{uc['slug']}")
    repo = state.repo_dir(S, uc["slug"]); V = S["verify"]
    hpaths = V.get("backend_health_paths") or [V.get("backend_health_path", "/health")]
    dockerUp, tail = (verify.compose_up(repo) if (repo / "docker-compose.yml").exists() else (False, "no compose"))
    backend_ok, hp = verify.health_check(V.get("backend_url", "http://localhost:8080"), hpaths,
                                         V["backend_health_timeout_s"]) if dockerUp else (False, None)
    web_ok, _ = verify.health_check(V.get("web_url", "http://localhost:3000"), ["/"], 60) if dockerUp else (False, None)
    web_dir = repo / "web" if (repo / "web").exists() else repo
    smoke = verify.run_e2e(V["e2e"].get("web", ""), web_dir)
    login_ok = smoke["passed"] if smoke["ran"] else web_ok  # honest fallback: page-200 if no e2e configured
    td = verify.compose_down(repo) if dockerUp else {"dockerCleanupDone": True}
    res = {"useCase": uc["name"], "ucSlug": uc["slug"], "dockerUp": dockerUp, "emulatorUp": False,
           "servicesHealthy": [{"name": "backend", "status": backend_ok, "healthPath": hp},
                               {"name": "web", "status": web_ok}],
           "allServicesHealthy": bool(backend_ok and web_ok),
           "loginSmokePassed": bool(login_ok), "loginSmokeMethod": "e2e" if smoke["ran"] else "page-200",
           "loginSmokeTail": smoke.get("tail", "")[-1200:],
           "teardownDone": td.get("dockerCleanupDone"), "bootEvidenceTail": tail}
    state.write(S, uc["slug"], "boot", res)
    if not gates.baseline_up(res):
        die_gate(f"baselineUp:{uc['slug']} (healthy={res['allServicesHealthy']}, smoke={res['loginSmokePassed']}) tag=agent")
    print(f"OK boot:{uc['slug']} healthy+smoke"); return res


def stage_push_main(S, uc):
    repo = state.repo_dir(S, uc["slug"])
    sh("gh", "repo", "create", uc["repo"], "--public")  # idempotent: no-op if exists (use cases are public)
    _, login = sh("gh", "api", "user", "-q", ".login"); owner = login.strip()
    git(repo, "remote", "remove", "origin"); git(repo, "remote", "add", "origin",
        f"https://github.com/{owner}/{uc['repo']}.git")
    code, out = git(repo, "push", "-u", "origin", "main")
    res = {"repo": uc["repo"], "owner": owner, "pushedMain": code == 0, "tail": out[-500:]}
    state.write(S, uc["slug"], "push-main", res)
    print(f"{'OK' if code==0 else 'WARN'} push-main:{uc['slug']} -> {owner}/{uc['repo']}"); return res


def stage_integrate(S, uc):
    if not gates.baseline_up(state.read(S, uc["slug"], "boot") or {}):
        die_gate(f"integrate needs GATE.baselineUp:{uc['slug']} — no integrating on a dead baseline")
    load_envfile_into_os()  # integration codegen needs the CometChat app creds
    if not os.environ.get("COMETCHAT_APP_ID"):
        die_gate(f"integrate:{uc['slug']} needs COMETCHAT_APP_ID — run provision-app first tag=agent")
    repo = state.repo_dir(S, uc["slug"]); logs = repo / "_logs"
    git(repo, "checkout", "-q", "main"); git(repo, "checkout", "-q", "-B", "feature/cometchat-integration")
    comps, worst, reports = prompts.expand_components(uc), 0, []
    for c in comps:
        cdir = repo / c["dir"]
        r = claude_runner.run_headless(prompts.render_integrate(S, uc, c), settings=S, phase="B",
                                       cwd=cdir, model_key="integrate", label=f"integrate-{c['name']}", log_dir=logs)
        g = verify.build_gate(c["kind"], cdir)
        rep = {"component": c["name"], "kind": c["kind"], "stack": c["stack"],
               "compileExitCode": g["buildExitCode"], "tokens": r["tokens"],
               "hitMaxTurns": r.get("hitMaxTurns"), "tail": g["outputTail"]}
        state.write(S, uc["slug"], f"report-{c['name']}", rep); reports.append(rep)
        worst = max(worst, g["buildExitCode"])  # compile is authoritative, not agent exit
    if worst == 0:
        git(repo, "add", "-A"); git(repo, "commit", "-q", "-m", f"CometChat integration {uc['name']}")
    gaps.rebuild(S)
    res = {"useCase": uc["name"], "slug": uc["slug"], "compileExitCode": worst, "reports": reports}
    state.write(S, uc["slug"], "integrate", res)
    if not gates.integrate(res):
        die_gate(f"integrate:{uc['slug']} (compileExit={worst}) tag=skills")
    print(f"OK integrate:{uc['slug']} compiled"); return res


def stage_verify(S, uc):
    if not gates.integrate(state.read(S, uc["slug"], "integrate") or {}):
        die_gate(f"verify needs GATE.integrate:{uc['slug']}")
    load_envfile_into_os()  # SDK init + compose need the creds
    repo = state.repo_dir(S, uc["slug"]); V = S["verify"]
    # STEP 1 — seed namespaced CometChat users + a conversation (deterministic 2-party chat)
    seed = cometchat.seed_conversation(str(ENV_FILE), uc["slug"])
    # STEP 2 — re-boot the integrated system
    hpaths = V.get("backend_health_paths") or [V.get("backend_health_path", "/health")]
    dockerUp, boot_tail = (verify.compose_up(repo) if (repo / "docker-compose.yml").exists() else (False, "no compose"))
    healthy, _ = verify.health_check(V.get("backend_url", "http://localhost:8080"), hpaths,
                                     V["backend_health_timeout_s"]) if dockerUp else (False, None)
    # STEP 3 — real chat/call e2e in the browser (login → open chat → send → call); bounded retry.
    # Accounts are the per-UC call-test pair (not mkt-hardcoded) — the web party logs into the browser.
    _acc = cometchat.call_test_accounts(uc["slug"])
    email = _acc["web"][0]; password = uc.get("e2ePassword", "Mkt@seed2026!")
    shot = str(repo / "_demo" / "web-call.png"); (repo / "_demo").mkdir(exist_ok=True)
    retry, e2e = 0, {}
    while retry <= S["max_retries"]:
        e2e = verify.run_chatcall_web(repo, email, password, V.get("web_url", "http://localhost:3000"), shot) if healthy else {"error": "not healthy"}
        if e2e.get("chatWorks") and e2e.get("callWorks"):
            break
        retry += 1
    sdk_ok = bool(e2e.get("sdkReady") or e2e.get("login"))          # SDK inited = CometChat login + list rendered (browser-proven)
    chat_ok, call_ok = bool(e2e.get("chatWorks")), bool(e2e.get("callWorks"))
    # STEP 4 — TWO-PARTY call matrix (web↔web voice+video: caller rings, callee accepts, both connect).
    # The android↔web / ios↔web legs are exercised hands-on in the manual demo (CP2) — two-party
    # mobile↔web call automation isn't proven, so we record those legs as manual rather than fake them.
    caller_email, callee_email = _acc["web"][0], _acc["mobile"][0]   # per-UC call-test pair
    matrix = verify.run_twoparty_web(repo, V.get("web_url", "http://localhost:3000"),
                                     str(repo / "_demo"), caller_email, callee_email, password,
                                     env_file=str(ENV_FILE), slug=uc["slug"]) if healthy else {"ok": False, "error": "not healthy"}
    call_matrix = {
        "web-web": {"voice": bool(matrix.get("voice", {}).get("callWorks")),
                    "video": bool(matrix.get("video", {}).get("callWorks")), "mode": "automated"},
        "android-web": {"mode": "manual-demo", "note": "verify hands-on at CP2 (emulator↔web)"},
        "ios-web": {"mode": "manual-demo", "note": "verify hands-on at CP2 (simulator↔web)"},
    }
    twoparty_ok = bool(matrix.get("ok"))
    # STEP 5 — AI moderation probe (functional: send flagged content, observe if masked/blocked/flagged)
    moderation = cometchat.check_moderation(str(ENV_FILE), uc["slug"]) if healthy else {"active": False, "error": "not healthy"}
    # STEP 6 — VISION + BASELINE review of the captured screenshots (advisory, not a hard gate).
    # "is it correct?" (Claude-vision rubric) + "did it change?" (perceptual baseline). Catches the
    # visual bugs DOM selectors miss (bottom-left ring, chat bleed, app header over the call) and
    # emits a self-contained HTML gallery for CP review. Off by settings if verify.vision_review=false.
    shot_review = {"skipped": True}
    if healthy and S.get("verify", {}).get("vision_review", True):
        demo_dir = repo / "_demo"
        candidates = [("web-call", shot, "ongoing_call", "web ongoing call")]
        for tag in ("voice", "video"):
            candidates += [(f"callee-ringing-{tag}", str(demo_dir / f"callee-ringing-{tag}.png"), "incoming_ring", f"web {tag} incoming"),
                           (f"callee-ongoing-{tag}", str(demo_dir / f"callee-ongoing-{tag}.png"), "ongoing_call", f"web {tag} ongoing")]
        shots = [{"name": n, "path": p, "rubric": r, "context": c} for n, p, r, c in candidates if os.path.exists(p)]
        if shots:
            shot_review = shotreview.review(shots, uc["slug"], S, str(demo_dir / "shot-review.html"))
    integratedUp = bool(dockerUp and healthy and sdk_ok)
    refuted = not (chat_ok and call_ok)                              # objective machine evidence, not a self-report
    td = verify.compose_down(repo) if dockerUp else {"dockerCleanupDone": True}
    res = {"useCase": uc["name"], "slug": uc["slug"], "dockerUp": dockerUp, "emulatorUp": False,
           "allServicesHealthy": healthy, "sdkInitOk": sdk_ok, "integratedUp": integratedUp,
           "cometchatUsersSeeded": 2 if seed.get("ok") else 0,
           "chatWorks": chat_ok, "callWorks": call_ok, "refuted": refuted,
           "callMatrix": call_matrix, "twoPartyWebWorks": twoparty_ok,
           "moderation": {"active": moderation.get("active"), "detail": moderation.get("note"),
                          "masked": moderation.get("masked"), "blocked": moderation.get("blocked")},
           "reason": "chat+call proven in browser" if not refuted else f"e2e incomplete: {e2e}",
           "easeScore": 5 if (chat_ok and call_ok) else (3 if chat_ok else 1),
           "shotReview": {"allCorrect": shot_review.get("allCorrect"), "anyChanged": shot_review.get("anyChanged"),
                          "gallery": shot_review.get("gallery"), "results": shot_review.get("results")},
           "retryCount": retry, "dockerCleanupDone": td.get("dockerCleanupDone"), "e2e": e2e, "callScreenshot": shot}
    state.write(S, uc["slug"], "verify", res)
    # Classify each auto-detected issue by CAUSE before recording. The curated skills ledger
    # (gaps/<slug>.md) must contain ONLY genuine CometChat skills/SDK/docs gaps — never harness
    # failures, coverage notes, or dashboard-setup state. Everything auto-detected here is triage
    # material → it goes to pipeline-notes/<slug>.md, NOT the skills ledger. A human (or the
    # integrate agent's explicit `tag=skills`) promotes a real skills gap into gaps/.
    notes = []
    if refuted and dockerUp:
        err = str(e2e.get("error", "")) + str(e2e.get("pageErrors", ""))
        harness = any(k in err for k in ("ERR_MODULE", "ENOENT", "Cannot find", "Traceback", "spawn"))
        cause = "harness" if harness else "integration/verify"
        notes.append(f"[{cause}] chat/call e2e did not pass — {str(e2e)[:400]}")
    if healthy and not twoparty_ok:
        notes.append(f"[harness/coverage] two-party web↔web call matrix incomplete — {str(matrix)[:300]}")
    if healthy and not moderation.get("active"):
        notes.append(f"[setup] AI moderation not observed — {moderation.get('note')} "
                     f"(enable the moderation/data-masking extension in the CometChat dashboard)")
    if shot_review.get("allCorrect") is False:  # vision judge flagged a visual issue on a captured shot
        bad = [f"{r['name']}({','.join(r['failedChecks'])})" for r in shot_review.get("results", []) if r.get("correct") is False]
        notes.append(f"[visual] Claude-vision flagged shot(s): {', '.join(bad)} — see gallery {shot_review.get('gallery')}")
    if notes:
        notes_dir = os.path.join(os.path.dirname(os.path.expanduser(S["gaps_dir"])), "pipeline-notes")
        os.makedirs(notes_dir, exist_ok=True)
        with open(os.path.join(notes_dir, f"{uc['slug']}.md"), "a") as f:
            f.write(f"\n### auto-recorded verify triage ({uc['slug']})\n"
                    + "\n".join(f"- {n}" for n in notes) + "\n")
    if not gates.verify(res):
        die_gate(f"verify:{uc['slug']} (integratedUp={integratedUp}, refuted={refuted}) tag=skills")
    print(f"OK verify:{uc['slug']} chat={chat_ok} call={call_ok} "
          f"2party(v/vid)={call_matrix['web-web']['voice']}/{call_matrix['web-web']['video']} "
          f"mod={moderation.get('active')} vision={shot_review.get('allCorrect')} ease={res['easeScore']}"); return res


def stage_push_branch(S, uc):
    if not gates.verify(state.read(S, uc["slug"], "verify") or {}):
        die_gate(f"push-branch needs GATE.verify:{uc['slug']}")
    repo = state.repo_dir(S, uc["slug"])
    code, out = git(repo, "push", "-u", "origin", "feature/cometchat-integration")
    res = {"pushedBranch": code == 0, "tail": out[-500:]}
    state.write(S, uc["slug"], "push-branch", res)
    print(f"{'OK' if code==0 else 'WARN'} push-branch:{uc['slug']} — use case complete"); return res


def _parse_judge(text: str) -> dict:
    import re
    m = re.search(r"\{.*\}", text, re.S)
    try:
        return json.loads(m.group(0)) if m else {}
    except Exception:
        return {}


STAGES = {"preflight": stage_preflight, "provision-app": stage_provision,
          "build": stage_build, "containerize": stage_containerize, "boot": stage_boot,
          "demo": stage_demo, "teardown": stage_teardown,
          "push-main": stage_push_main, "integrate": stage_integrate,
          "verify": stage_verify, "push-branch": stage_push_branch}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--use-case", required=True)
    ap.add_argument("--stage", required=True, choices=list(STAGES))
    ap.add_argument("--settings", default="settings.json")
    args = ap.parse_args()
    S = load(args.settings)
    augment_path(S)  # make self-installed tools findable in every stage
    ucs = {u["slug"]: u for u in load("use_cases.json")["use_cases"]}
    if args.use_case not in ucs:
        print(f"unknown use case {args.use_case}", file=sys.stderr); sys.exit(3)
    try:
        STAGES[args.stage](S, ucs[args.use_case])
    except SystemExit:
        raise
    except Exception as e:
        import traceback; traceback.print_exc()
        print(f"STAGE-ERROR: {e}", file=sys.stderr); sys.exit(3)


if __name__ == "__main__":
    main()
